// Automatically generated from Google Drive ContentRsell Catalog
// Total Folders: 16 | Total Files: 194

export const CREATOR_FOLDERS_CATALOG = [
  {
    "id": "folder-cleo-01",
    "driveName": "Cleo - OF-Fansly",
    "coverKey": "cleo_of",
    "tierRequired": "bronze",
    "creator": "Cleo",
    "title": "Cleo - VIP Photo Archive",
    "tag": "PHOTO ARCHIVE",
    "category": "Verified Partner Creator",
    "description": "Official private sets and subscriber photoshoot archives directly from Cleo.",
    "qualityNote": "HD Mobile Camera Roll · Raw Capture",
    "mediaType": "photo",
    "driveFolderId": "1rndY6lWTRPTJDbWk850e7TVH9BZ9CelX",
    "coverImage": "/vault/covers/cleo_of.jpg",
    "itemCount": "20 Photos",
    "filesCount": 20,
    "files": [
      {
        "id": "1eBlRFSN-_TZY0mCQg9YZZ6xNsP_n5Ftr",
        "name": "Cleo_20.png",
        "meta": "1.5 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1eBlRFSN-_TZY0mCQg9YZZ6xNsP_n5Ftr.jpg",
        "fullUrl": "/vault/content/1eBlRFSN-_TZY0mCQg9YZZ6xNsP_n5Ftr.jpg",
        "directViewUrl": "/vault/content/1eBlRFSN-_TZY0mCQg9YZZ6xNsP_n5Ftr.jpg"
      },
      {
        "id": "1I7ZIEq4zWL8kYd0KjoJbVffPipsU8jcF",
        "name": "Cleo_21.png",
        "meta": "1.5 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1I7ZIEq4zWL8kYd0KjoJbVffPipsU8jcF.jpg",
        "fullUrl": "/vault/content/1I7ZIEq4zWL8kYd0KjoJbVffPipsU8jcF.jpg",
        "directViewUrl": "/vault/content/1I7ZIEq4zWL8kYd0KjoJbVffPipsU8jcF.jpg"
      },
      {
        "id": "1sSGv1Zy1O4scS2E_FZzPcB7Chu7OXE1A",
        "name": "Cleo_22.png",
        "meta": "996 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1sSGv1Zy1O4scS2E_FZzPcB7Chu7OXE1A.jpg",
        "fullUrl": "/vault/content/1sSGv1Zy1O4scS2E_FZzPcB7Chu7OXE1A.jpg",
        "directViewUrl": "/vault/content/1sSGv1Zy1O4scS2E_FZzPcB7Chu7OXE1A.jpg"
      },
      {
        "id": "1jVDs0kR-QSBKfyfpXX_0e9JWoKa9jJCj",
        "name": "Cleo_23.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1jVDs0kR-QSBKfyfpXX_0e9JWoKa9jJCj.jpg",
        "fullUrl": "/vault/content/1jVDs0kR-QSBKfyfpXX_0e9JWoKa9jJCj.jpg",
        "directViewUrl": "/vault/content/1jVDs0kR-QSBKfyfpXX_0e9JWoKa9jJCj.jpg"
      },
      {
        "id": "1SbuqeGbOEVfYFl-rP-Ob3gZ1cn5zdVm3",
        "name": "Cleo_24.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1SbuqeGbOEVfYFl-rP-Ob3gZ1cn5zdVm3.jpg",
        "fullUrl": "/vault/content/1SbuqeGbOEVfYFl-rP-Ob3gZ1cn5zdVm3.jpg",
        "directViewUrl": "/vault/content/1SbuqeGbOEVfYFl-rP-Ob3gZ1cn5zdVm3.jpg"
      },
      {
        "id": "18U8wQC_r66EfhD1xsw3IneAfuo3LmS8P",
        "name": "Cleo_25.png",
        "meta": "752 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/18U8wQC_r66EfhD1xsw3IneAfuo3LmS8P.jpg",
        "fullUrl": "/vault/content/18U8wQC_r66EfhD1xsw3IneAfuo3LmS8P.jpg",
        "directViewUrl": "/vault/content/18U8wQC_r66EfhD1xsw3IneAfuo3LmS8P.jpg"
      },
      {
        "id": "1UW9gwDwd6RO3Y9a4Ep4qDE-BOKj1gKSm",
        "name": "Cleo_26.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1UW9gwDwd6RO3Y9a4Ep4qDE-BOKj1gKSm.jpg",
        "fullUrl": "/vault/content/1UW9gwDwd6RO3Y9a4Ep4qDE-BOKj1gKSm.jpg",
        "directViewUrl": "/vault/content/1UW9gwDwd6RO3Y9a4Ep4qDE-BOKj1gKSm.jpg"
      },
      {
        "id": "18npJqdjfGmsSMxBDoKAVC44oTRNYDT_J",
        "name": "Cleo_27.png",
        "meta": "871 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/18npJqdjfGmsSMxBDoKAVC44oTRNYDT_J.jpg",
        "fullUrl": "/vault/content/18npJqdjfGmsSMxBDoKAVC44oTRNYDT_J.jpg",
        "directViewUrl": "/vault/content/18npJqdjfGmsSMxBDoKAVC44oTRNYDT_J.jpg"
      },
      {
        "id": "16nGZkcdDVaqy8IMph-eniDyHcT3p7JG0",
        "name": "Cleo_28.png",
        "meta": "1.5 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/16nGZkcdDVaqy8IMph-eniDyHcT3p7JG0.jpg",
        "fullUrl": "/vault/content/16nGZkcdDVaqy8IMph-eniDyHcT3p7JG0.jpg",
        "directViewUrl": "/vault/content/16nGZkcdDVaqy8IMph-eniDyHcT3p7JG0.jpg"
      },
      {
        "id": "1cOJKj761MZc-98np62nXF50r0pX1UPOL",
        "name": "Cleo_29.png",
        "meta": "1 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1cOJKj761MZc-98np62nXF50r0pX1UPOL.jpg",
        "fullUrl": "/vault/content/1cOJKj761MZc-98np62nXF50r0pX1UPOL.jpg",
        "directViewUrl": "/vault/content/1cOJKj761MZc-98np62nXF50r0pX1UPOL.jpg"
      },
      {
        "id": "1xeu2LUy83ZT1kynQdSe-1q8h1kzkw8q-",
        "name": "Cloe_01.png",
        "meta": "1.5 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1xeu2LUy83ZT1kynQdSe-1q8h1kzkw8q-.jpg",
        "fullUrl": "/vault/content/1xeu2LUy83ZT1kynQdSe-1q8h1kzkw8q-.jpg",
        "directViewUrl": "/vault/content/1xeu2LUy83ZT1kynQdSe-1q8h1kzkw8q-.jpg"
      },
      {
        "id": "1TgD6NpowFRPfanULA-j3aQ0F4E9w0EN2",
        "name": "Cloe_02.png",
        "meta": "1.3 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1TgD6NpowFRPfanULA-j3aQ0F4E9w0EN2.jpg",
        "fullUrl": "/vault/content/1TgD6NpowFRPfanULA-j3aQ0F4E9w0EN2.jpg",
        "directViewUrl": "/vault/content/1TgD6NpowFRPfanULA-j3aQ0F4E9w0EN2.jpg"
      },
      {
        "id": "1IGFnnKwr7WXKzUT3ek5iTKbASGLs1MT4",
        "name": "Cloe_03.png",
        "meta": "1.3 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1IGFnnKwr7WXKzUT3ek5iTKbASGLs1MT4.jpg",
        "fullUrl": "/vault/content/1IGFnnKwr7WXKzUT3ek5iTKbASGLs1MT4.jpg",
        "directViewUrl": "/vault/content/1IGFnnKwr7WXKzUT3ek5iTKbASGLs1MT4.jpg"
      },
      {
        "id": "1EkSxGPmUXbnkMfmogMM68mc_MXvG80ky",
        "name": "Cloe_04.png",
        "meta": "1.5 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1EkSxGPmUXbnkMfmogMM68mc_MXvG80ky.jpg",
        "fullUrl": "/vault/content/1EkSxGPmUXbnkMfmogMM68mc_MXvG80ky.jpg",
        "directViewUrl": "/vault/content/1EkSxGPmUXbnkMfmogMM68mc_MXvG80ky.jpg"
      },
      {
        "id": "1pOrGVmbQlulgYZVQ-7UpGj2MMO6Zm6qb",
        "name": "Cloe_05.png",
        "meta": "1.5 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1pOrGVmbQlulgYZVQ-7UpGj2MMO6Zm6qb.jpg",
        "fullUrl": "/vault/content/1pOrGVmbQlulgYZVQ-7UpGj2MMO6Zm6qb.jpg",
        "directViewUrl": "/vault/content/1pOrGVmbQlulgYZVQ-7UpGj2MMO6Zm6qb.jpg"
      },
      {
        "id": "1BCyPBy-Sljs7fFkfseKGWiC-wiZM_GWa",
        "name": "Cloe_06.png",
        "meta": "1.3 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1BCyPBy-Sljs7fFkfseKGWiC-wiZM_GWa.jpg",
        "fullUrl": "/vault/content/1BCyPBy-Sljs7fFkfseKGWiC-wiZM_GWa.jpg",
        "directViewUrl": "/vault/content/1BCyPBy-Sljs7fFkfseKGWiC-wiZM_GWa.jpg"
      },
      {
        "id": "1UFO3S8sxIoc6rzGnLTe1rmzd3ZtvqmUb",
        "name": "Cloe_07.png",
        "meta": "2.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1UFO3S8sxIoc6rzGnLTe1rmzd3ZtvqmUb.jpg",
        "fullUrl": "/vault/content/1UFO3S8sxIoc6rzGnLTe1rmzd3ZtvqmUb.jpg",
        "directViewUrl": "/vault/content/1UFO3S8sxIoc6rzGnLTe1rmzd3ZtvqmUb.jpg"
      },
      {
        "id": "14h-7HqQ9z6UNqcYIlC_amXpQ-vw6t8Wr",
        "name": "Cloe_08.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/14h-7HqQ9z6UNqcYIlC_amXpQ-vw6t8Wr.jpg",
        "fullUrl": "/vault/content/14h-7HqQ9z6UNqcYIlC_amXpQ-vw6t8Wr.jpg",
        "directViewUrl": "/vault/content/14h-7HqQ9z6UNqcYIlC_amXpQ-vw6t8Wr.jpg"
      },
      {
        "id": "1i_u_MbNgxGVuuMSRANdFG3upx1q-etB7",
        "name": "Cloe_09.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1i_u_MbNgxGVuuMSRANdFG3upx1q-etB7.jpg",
        "fullUrl": "/vault/content/1i_u_MbNgxGVuuMSRANdFG3upx1q-etB7.jpg",
        "directViewUrl": "/vault/content/1i_u_MbNgxGVuuMSRANdFG3upx1q-etB7.jpg"
      },
      {
        "id": "1NyKGbNUq9MFRX3ph2LFhneKtvyV-tJIL",
        "name": "Cloe_10.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1NyKGbNUq9MFRX3ph2LFhneKtvyV-tJIL.jpg",
        "fullUrl": "/vault/content/1NyKGbNUq9MFRX3ph2LFhneKtvyV-tJIL.jpg",
        "directViewUrl": "/vault/content/1NyKGbNUq9MFRX3ph2LFhneKtvyV-tJIL.jpg"
      }
    ]
  },
  {
    "id": "folder-elachar-01",
    "driveName": "ElaChar - Videa - CUT DONE",
    "coverKey": "elachar_videa",
    "tierRequired": "bronze",
    "creator": "ElaChar",
    "title": "ElaChar - Master Studio Cuts",
    "tag": "STUDIO CUTS",
    "category": "Verified Partner Creator",
    "description": "Finished and mastered private studio sessions filmed in collaboration with the platform.",
    "qualityNote": "1080p Studio Edit · Master Cuts",
    "mediaType": "video",
    "driveFolderId": "1pFX43jWwEy9_eAuXKGxYkBgoxs2v19Gv",
    "coverImage": "/vault/covers/elachar_videa.jpg",
    "itemCount": "15 Videos",
    "filesCount": 15,
    "files": [
      {
        "id": "157gHUMfO20s5760RUhPuDyeGWMLMUy4a",
        "name": "0108(5).mp4",
        "meta": "119 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/157gHUMfO20s5760RUhPuDyeGWMLMUy4a.jpg",
        "fullUrl": "/vault/content/157gHUMfO20s5760RUhPuDyeGWMLMUy4a.jpg",
        "directViewUrl": "/vault/content/157gHUMfO20s5760RUhPuDyeGWMLMUy4a.jpg",
        "videoUrl": "/vault/videos/157gHUMfO20s5760RUhPuDyeGWMLMUy4a.mp4"
      },
      {
        "id": "1oXidl-FXrLpVXDNoXOYOBte3Fv5wNhHp",
        "name": "ElaChar - BG-riding on him.mp4",
        "meta": "70.4 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1oXidl-FXrLpVXDNoXOYOBte3Fv5wNhHp.jpg",
        "fullUrl": "/vault/content/1oXidl-FXrLpVXDNoXOYOBte3Fv5wNhHp.jpg",
        "directViewUrl": "/vault/content/1oXidl-FXrLpVXDNoXOYOBte3Fv5wNhHp.jpg",
        "videoUrl": "/vault/videos/1oXidl-FXrLpVXDNoXOYOBte3Fv5wNhHp.mp4"
      },
      {
        "id": "1C28rpGmGAw3-XyLhRMDnetI_DqskKxNH",
        "name": "ElaChar - BG(sex,bj) - 10mn.mp4",
        "meta": "1.24 GB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1C28rpGmGAw3-XyLhRMDnetI_DqskKxNH.jpg",
        "fullUrl": "/vault/content/1C28rpGmGAw3-XyLhRMDnetI_DqskKxNH.jpg",
        "directViewUrl": "/vault/content/1C28rpGmGAw3-XyLhRMDnetI_DqskKxNH.jpg",
        "videoUrl": "/vault/videos/1C28rpGmGAw3-XyLhRMDnetI_DqskKxNH.mp4"
      },
      {
        "id": "1XK86KsjMsvUdlDm5utGfkUASpR1Uzr6R",
        "name": "ElaChar - BJ - long.mp4",
        "meta": "382.9 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1XK86KsjMsvUdlDm5utGfkUASpR1Uzr6R.jpg",
        "fullUrl": "/vault/content/1XK86KsjMsvUdlDm5utGfkUASpR1Uzr6R.jpg",
        "directViewUrl": "/vault/content/1XK86KsjMsvUdlDm5utGfkUASpR1Uzr6R.jpg",
        "videoUrl": "/vault/videos/1XK86KsjMsvUdlDm5utGfkUASpR1Uzr6R.mp4"
      },
      {
        "id": "1aqSV1SAGT2YNX4AfZJLSvEzP_n8blDzV",
        "name": "ElaChar - BJ+Sex+Cumshot - long.mp4",
        "meta": "783.4 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1aqSV1SAGT2YNX4AfZJLSvEzP_n8blDzV.jpg",
        "fullUrl": "/vault/content/1aqSV1SAGT2YNX4AfZJLSvEzP_n8blDzV.jpg",
        "directViewUrl": "/vault/content/1aqSV1SAGT2YNX4AfZJLSvEzP_n8blDzV.jpg",
        "videoUrl": "/vault/videos/1aqSV1SAGT2YNX4AfZJLSvEzP_n8blDzV.mp4"
      },
      {
        "id": "1CmQ5yAhHtcGds_WjXpmt33C9g8Sb3qWt",
        "name": "ElaChar - BJ2.mp4",
        "meta": "437 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1CmQ5yAhHtcGds_WjXpmt33C9g8Sb3qWt.jpg",
        "fullUrl": "/vault/content/1CmQ5yAhHtcGds_WjXpmt33C9g8Sb3qWt.jpg",
        "directViewUrl": "/vault/content/1CmQ5yAhHtcGds_WjXpmt33C9g8Sb3qWt.jpg",
        "videoUrl": "/vault/videos/1CmQ5yAhHtcGds_WjXpmt33C9g8Sb3qWt.mp4"
      },
      {
        "id": "1OMzOGTUoUZyrwsDjq-9SuCAkSKEBEAi1",
        "name": "ElaChar - FullyNude - boobplay(short) - BAD CUT!!!!!!.mp4",
        "meta": "24.3 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1OMzOGTUoUZyrwsDjq-9SuCAkSKEBEAi1.jpg",
        "fullUrl": "/vault/content/1OMzOGTUoUZyrwsDjq-9SuCAkSKEBEAi1.jpg",
        "directViewUrl": "/vault/content/1OMzOGTUoUZyrwsDjq-9SuCAkSKEBEAi1.jpg",
        "videoUrl": "/vault/videos/1OMzOGTUoUZyrwsDjq-9SuCAkSKEBEAi1.mp4"
      },
      {
        "id": "1-2H5cO-Q1sgg748GvN26RxtcJtIlq3wp",
        "name": "ElaChar - Fullynude - Boobplay+Pussy(best).mp4",
        "meta": "57.6 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1-2H5cO-Q1sgg748GvN26RxtcJtIlq3wp.jpg",
        "fullUrl": "/vault/content/1-2H5cO-Q1sgg748GvN26RxtcJtIlq3wp.jpg",
        "directViewUrl": "/vault/content/1-2H5cO-Q1sgg748GvN26RxtcJtIlq3wp.jpg",
        "videoUrl": "/vault/videos/1-2H5cO-Q1sgg748GvN26RxtcJtIlq3wp.mp4"
      },
      {
        "id": "1Ds2_VJHa70UJtsRksdGM1Ggr4HvuxE91",
        "name": "Elachar - Fullynude - Boobplay+Pussy(long).mp4",
        "meta": "85.6 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1Ds2_VJHa70UJtsRksdGM1Ggr4HvuxE91.jpg",
        "fullUrl": "/vault/content/1Ds2_VJHa70UJtsRksdGM1Ggr4HvuxE91.jpg",
        "directViewUrl": "/vault/content/1Ds2_VJHa70UJtsRksdGM1Ggr4HvuxE91.jpg",
        "videoUrl": "/vault/videos/1Ds2_VJHa70UJtsRksdGM1Ggr4HvuxE91.mp4"
      },
      {
        "id": "1DbyvVPkVXjNYT5V_KFTdYcRQO5FLgAhb",
        "name": "ElaChar - JOI - long.mp4",
        "meta": "551.8 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1DbyvVPkVXjNYT5V_KFTdYcRQO5FLgAhb.jpg",
        "fullUrl": "/vault/content/1DbyvVPkVXjNYT5V_KFTdYcRQO5FLgAhb.jpg",
        "directViewUrl": "/vault/content/1DbyvVPkVXjNYT5V_KFTdYcRQO5FLgAhb.jpg",
        "videoUrl": "/vault/videos/1DbyvVPkVXjNYT5V_KFTdYcRQO5FLgAhb.mp4"
      },
      {
        "id": "1etBBs96RtE3qHp59Kj_35M50oJAagflM",
        "name": "ElaChar - On bed - Dirty talk(long) - BAD CUT!!!!!!.mp4",
        "meta": "578.9 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1etBBs96RtE3qHp59Kj_35M50oJAagflM.jpg",
        "fullUrl": "/vault/content/1etBBs96RtE3qHp59Kj_35M50oJAagflM.jpg",
        "directViewUrl": "/vault/content/1etBBs96RtE3qHp59Kj_35M50oJAagflM.jpg",
        "videoUrl": "/vault/videos/1etBBs96RtE3qHp59Kj_35M50oJAagflM.mp4"
      },
      {
        "id": "1XxDiT6AGmexLLi6lN1tPtJipuxPazTt5",
        "name": "ElaChar - Pussyplay(before squirt).mp4",
        "meta": "9.7 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1XxDiT6AGmexLLi6lN1tPtJipuxPazTt5.jpg",
        "fullUrl": "/vault/content/1XxDiT6AGmexLLi6lN1tPtJipuxPazTt5.jpg",
        "directViewUrl": "/vault/content/1XxDiT6AGmexLLi6lN1tPtJipuxPazTt5.jpg",
        "videoUrl": "/vault/videos/1XxDiT6AGmexLLi6lN1tPtJipuxPazTt5.mp4"
      },
      {
        "id": "1qqeYnTKmD4hJmNnPXGZVV3Lrv4VmQ2Mh",
        "name": "ElaChar - Squirt+Dildo(long) - NO SOUND.mp4",
        "meta": "230.3 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1qqeYnTKmD4hJmNnPXGZVV3Lrv4VmQ2Mh.jpg",
        "fullUrl": "/vault/content/1qqeYnTKmD4hJmNnPXGZVV3Lrv4VmQ2Mh.jpg",
        "directViewUrl": "/vault/content/1qqeYnTKmD4hJmNnPXGZVV3Lrv4VmQ2Mh.jpg",
        "videoUrl": "/vault/videos/1qqeYnTKmD4hJmNnPXGZVV3Lrv4VmQ2Mh.mp4"
      },
      {
        "id": "1jXsxQtgpaeo7J3ViMPq_7NdaUCjk51fB",
        "name": "ElaChar - Squirt+Dildo(short) - NO SOUND!!!.mp4",
        "meta": "31.2 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1jXsxQtgpaeo7J3ViMPq_7NdaUCjk51fB.jpg",
        "fullUrl": "/vault/content/1jXsxQtgpaeo7J3ViMPq_7NdaUCjk51fB.jpg",
        "directViewUrl": "/vault/content/1jXsxQtgpaeo7J3ViMPq_7NdaUCjk51fB.jpg",
        "videoUrl": "/vault/videos/1jXsxQtgpaeo7J3ViMPq_7NdaUCjk51fB.mp4"
      },
      {
        "id": "19fNTDxdU_xtHenXk8MnXInm_ZdVccb6q",
        "name": "ElaChar - Squirt+Dildo(short).mp4",
        "meta": "5.4 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/19fNTDxdU_xtHenXk8MnXInm_ZdVccb6q.jpg",
        "fullUrl": "/vault/content/19fNTDxdU_xtHenXk8MnXInm_ZdVccb6q.jpg",
        "directViewUrl": "/vault/content/19fNTDxdU_xtHenXk8MnXInm_ZdVccb6q.jpg",
        "videoUrl": "/vault/videos/19fNTDxdU_xtHenXk8MnXInm_ZdVccb6q.mp4"
      }
    ]
  },
  {
    "id": "folder-melissa-01",
    "driveName": "Melissa - OF - Fansly",
    "coverKey": "melissa_of",
    "tierRequired": "bronze",
    "creator": "Melissa",
    "title": "Melissa - Signature VIP Set",
    "tag": "SIGNATURE SET",
    "category": "Verified Partner Creator",
    "description": "Exclusive subscribers-only high-resolution photo sets from Melissa.",
    "qualityNote": "Direct Feed Export · High Resolution",
    "mediaType": "photo",
    "driveFolderId": "1IgynUiqAPcAZoFS8eRYbmfMb4ZgpWapm",
    "coverImage": "/vault/covers/melissa_of.jpg",
    "itemCount": "20 Photos",
    "filesCount": 20,
    "files": [
      {
        "id": "1NKqAn7gnPMTz9rOyO4G1dtGx0PqikRoE",
        "name": "Melissa_01.png",
        "meta": "001 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1NKqAn7gnPMTz9rOyO4G1dtGx0PqikRoE.jpg",
        "fullUrl": "/vault/content/1NKqAn7gnPMTz9rOyO4G1dtGx0PqikRoE.jpg",
        "directViewUrl": "/vault/content/1NKqAn7gnPMTz9rOyO4G1dtGx0PqikRoE.jpg"
      },
      {
        "id": "1-w_cCjfKoNmX_WGlNzivfzCfKS9JTD1k",
        "name": "Melissa_02.png",
        "meta": "013 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1-w_cCjfKoNmX_WGlNzivfzCfKS9JTD1k.jpg",
        "fullUrl": "/vault/content/1-w_cCjfKoNmX_WGlNzivfzCfKS9JTD1k.jpg",
        "directViewUrl": "/vault/content/1-w_cCjfKoNmX_WGlNzivfzCfKS9JTD1k.jpg"
      },
      {
        "id": "1wIpTZ0wtUJdG5MkBLRSNGtbst8aolKyF",
        "name": "Melissa_03.png",
        "meta": "871 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1wIpTZ0wtUJdG5MkBLRSNGtbst8aolKyF.jpg",
        "fullUrl": "/vault/content/1wIpTZ0wtUJdG5MkBLRSNGtbst8aolKyF.jpg",
        "directViewUrl": "/vault/content/1wIpTZ0wtUJdG5MkBLRSNGtbst8aolKyF.jpg"
      },
      {
        "id": "1Y0FuWISfb7OcXK_-4_BafXbtfvl98mJP",
        "name": "Melissa_04.png",
        "meta": "662 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1Y0FuWISfb7OcXK_-4_BafXbtfvl98mJP.jpg",
        "fullUrl": "/vault/content/1Y0FuWISfb7OcXK_-4_BafXbtfvl98mJP.jpg",
        "directViewUrl": "/vault/content/1Y0FuWISfb7OcXK_-4_BafXbtfvl98mJP.jpg"
      },
      {
        "id": "1wAvgGkZp8Jj-5cglXseI6Pfeo2Z5wRhH",
        "name": "Melissa_05.png",
        "meta": "845 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1wAvgGkZp8Jj-5cglXseI6Pfeo2Z5wRhH.jpg",
        "fullUrl": "/vault/content/1wAvgGkZp8Jj-5cglXseI6Pfeo2Z5wRhH.jpg",
        "directViewUrl": "/vault/content/1wAvgGkZp8Jj-5cglXseI6Pfeo2Z5wRhH.jpg"
      },
      {
        "id": "1Uk1q0kX804lXH68q9awXchcWmlo2eKSt",
        "name": "Melissa_06.png",
        "meta": "009 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1Uk1q0kX804lXH68q9awXchcWmlo2eKSt.jpg",
        "fullUrl": "/vault/content/1Uk1q0kX804lXH68q9awXchcWmlo2eKSt.jpg",
        "directViewUrl": "/vault/content/1Uk1q0kX804lXH68q9awXchcWmlo2eKSt.jpg"
      },
      {
        "id": "1ZPQGttuMT1KB70wZxlmJaRDQb6Z5pDP4",
        "name": "Melissa_07.png",
        "meta": "979 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1ZPQGttuMT1KB70wZxlmJaRDQb6Z5pDP4.jpg",
        "fullUrl": "/vault/content/1ZPQGttuMT1KB70wZxlmJaRDQb6Z5pDP4.jpg",
        "directViewUrl": "/vault/content/1ZPQGttuMT1KB70wZxlmJaRDQb6Z5pDP4.jpg"
      },
      {
        "id": "19DrzeJcfnOtPSMPlWiZZPpbHg-97kE_s",
        "name": "Melissa_08.png",
        "meta": "1.1 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/19DrzeJcfnOtPSMPlWiZZPpbHg-97kE_s.jpg",
        "fullUrl": "/vault/content/19DrzeJcfnOtPSMPlWiZZPpbHg-97kE_s.jpg",
        "directViewUrl": "/vault/content/19DrzeJcfnOtPSMPlWiZZPpbHg-97kE_s.jpg"
      },
      {
        "id": "1sF6u1sxYK62nNe60KMq_Tm09pN9Rcej7",
        "name": "Melissa_09.png",
        "meta": "829 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1sF6u1sxYK62nNe60KMq_Tm09pN9Rcej7.jpg",
        "fullUrl": "/vault/content/1sF6u1sxYK62nNe60KMq_Tm09pN9Rcej7.jpg",
        "directViewUrl": "/vault/content/1sF6u1sxYK62nNe60KMq_Tm09pN9Rcej7.jpg"
      },
      {
        "id": "16fVCooiCXBaDSCzCpYZPu7QKLDOxO96M",
        "name": "Melissa_10.png",
        "meta": "005 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/16fVCooiCXBaDSCzCpYZPu7QKLDOxO96M.jpg",
        "fullUrl": "/vault/content/16fVCooiCXBaDSCzCpYZPu7QKLDOxO96M.jpg",
        "directViewUrl": "/vault/content/16fVCooiCXBaDSCzCpYZPu7QKLDOxO96M.jpg"
      },
      {
        "id": "1CPl3ojrdMTjIXaXnml0qVjf6txqEOgpZ",
        "name": "Melissa_11.png",
        "meta": "1.1 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1CPl3ojrdMTjIXaXnml0qVjf6txqEOgpZ.jpg",
        "fullUrl": "/vault/content/1CPl3ojrdMTjIXaXnml0qVjf6txqEOgpZ.jpg",
        "directViewUrl": "/vault/content/1CPl3ojrdMTjIXaXnml0qVjf6txqEOgpZ.jpg"
      },
      {
        "id": "1E1mzNnr5ZXzUvbRY2eVzt2q_HNKe2uFL",
        "name": "Melissa_12.png",
        "meta": "896 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1E1mzNnr5ZXzUvbRY2eVzt2q_HNKe2uFL.jpg",
        "fullUrl": "/vault/content/1E1mzNnr5ZXzUvbRY2eVzt2q_HNKe2uFL.jpg",
        "directViewUrl": "/vault/content/1E1mzNnr5ZXzUvbRY2eVzt2q_HNKe2uFL.jpg"
      },
      {
        "id": "1Plx3sfbM4zvfS2FDEz8vAMwk7ocUZesv",
        "name": "Melissa_13.png",
        "meta": "941 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1Plx3sfbM4zvfS2FDEz8vAMwk7ocUZesv.jpg",
        "fullUrl": "/vault/content/1Plx3sfbM4zvfS2FDEz8vAMwk7ocUZesv.jpg",
        "directViewUrl": "/vault/content/1Plx3sfbM4zvfS2FDEz8vAMwk7ocUZesv.jpg"
      },
      {
        "id": "1t_j_i2G52_242PhAufP9JKTLPpXJdOVD",
        "name": "Melissa_14.png",
        "meta": "3.1 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1t_j_i2G52_242PhAufP9JKTLPpXJdOVD.jpg",
        "fullUrl": "/vault/content/1t_j_i2G52_242PhAufP9JKTLPpXJdOVD.jpg",
        "directViewUrl": "/vault/content/1t_j_i2G52_242PhAufP9JKTLPpXJdOVD.jpg"
      },
      {
        "id": "1NOozsV0NxPfI7Albw-JqqF9ZEv1c1WnA",
        "name": "Melissa_15.png",
        "meta": "018 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1NOozsV0NxPfI7Albw-JqqF9ZEv1c1WnA.jpg",
        "fullUrl": "/vault/content/1NOozsV0NxPfI7Albw-JqqF9ZEv1c1WnA.jpg",
        "directViewUrl": "/vault/content/1NOozsV0NxPfI7Albw-JqqF9ZEv1c1WnA.jpg"
      },
      {
        "id": "1GtpyFeTPm4XEI1w9U8_B6GnR8phxNZsu",
        "name": "Melissa_16.png",
        "meta": "1.1 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1GtpyFeTPm4XEI1w9U8_B6GnR8phxNZsu.jpg",
        "fullUrl": "/vault/content/1GtpyFeTPm4XEI1w9U8_B6GnR8phxNZsu.jpg",
        "directViewUrl": "/vault/content/1GtpyFeTPm4XEI1w9U8_B6GnR8phxNZsu.jpg"
      },
      {
        "id": "1vhJ-7nhG9n-wGuwlDWx1sva63PlIX000",
        "name": "Melissa_17.png",
        "meta": "1.1 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1vhJ-7nhG9n-wGuwlDWx1sva63PlIX000.jpg",
        "fullUrl": "/vault/content/1vhJ-7nhG9n-wGuwlDWx1sva63PlIX000.jpg",
        "directViewUrl": "/vault/content/1vhJ-7nhG9n-wGuwlDWx1sva63PlIX000.jpg"
      },
      {
        "id": "1kMU0tRhdedOnb3UnZCZHhR-MG8IIdtpe",
        "name": "Melissa_18.png",
        "meta": "1.1 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1kMU0tRhdedOnb3UnZCZHhR-MG8IIdtpe.jpg",
        "fullUrl": "/vault/content/1kMU0tRhdedOnb3UnZCZHhR-MG8IIdtpe.jpg",
        "directViewUrl": "/vault/content/1kMU0tRhdedOnb3UnZCZHhR-MG8IIdtpe.jpg"
      },
      {
        "id": "1pTyxiIjFk1nSgsYavVaFCtmGMD-tmjwZ",
        "name": "Melissa_doggyfake.png",
        "meta": "952 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1pTyxiIjFk1nSgsYavVaFCtmGMD-tmjwZ.jpg",
        "fullUrl": "/vault/content/1pTyxiIjFk1nSgsYavVaFCtmGMD-tmjwZ.jpg",
        "directViewUrl": "/vault/content/1pTyxiIjFk1nSgsYavVaFCtmGMD-tmjwZ.jpg"
      },
      {
        "id": "1kmR_9ThhqJQ14rkP2V5EpZdik3sd7P7_",
        "name": "Melissa_feet1.png",
        "meta": "1.3 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1kmR_9ThhqJQ14rkP2V5EpZdik3sd7P7_.jpg",
        "fullUrl": "/vault/content/1kmR_9ThhqJQ14rkP2V5EpZdik3sd7P7_.jpg",
        "directViewUrl": "/vault/content/1kmR_9ThhqJQ14rkP2V5EpZdik3sd7P7_.jpg"
      }
    ]
  },
  {
    "id": "folder-tessa-01",
    "driveName": "Tessa",
    "coverKey": "tessa_of",
    "tierRequired": "bronze",
    "creator": "Tessa",
    "title": "Tessa - VIP Photobook Archive",
    "tag": "PHOTOBOOK",
    "category": "Verified Partner Creator",
    "description": "Full resolution unreleased photo shoots and camera roll captures from Tessa.",
    "qualityNote": "Authentic Unfiltered Photos",
    "mediaType": "photo",
    "driveFolderId": "1bfbhguGUf2zqQxEKxQvUVQqLLpJat8f2",
    "coverImage": "/vault/covers/tessa_of.jpg",
    "itemCount": "20 Photos",
    "filesCount": 20,
    "files": [
      {
        "id": "1cOwDqVnOkncqTYP4am1lAabmp5bIRk3d",
        "name": "ass_beach.png",
        "meta": "1.8 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1cOwDqVnOkncqTYP4am1lAabmp5bIRk3d.jpg",
        "fullUrl": "/vault/content/1cOwDqVnOkncqTYP4am1lAabmp5bIRk3d.jpg",
        "directViewUrl": "/vault/content/1cOwDqVnOkncqTYP4am1lAabmp5bIRk3d.jpg"
      },
      {
        "id": "1deQqh8OsYX4oTyrkNjbBHSd2-eenfeq1",
        "name": "bathtub_tease.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1deQqh8OsYX4oTyrkNjbBHSd2-eenfeq1.jpg",
        "fullUrl": "/vault/content/1deQqh8OsYX4oTyrkNjbBHSd2-eenfeq1.jpg",
        "directViewUrl": "/vault/content/1deQqh8OsYX4oTyrkNjbBHSd2-eenfeq1.jpg"
      },
      {
        "id": "1jrBhm0Ccu4fPFK069oOdu9rAr30LSqgE",
        "name": "beach.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1jrBhm0Ccu4fPFK069oOdu9rAr30LSqgE.jpg",
        "fullUrl": "/vault/content/1jrBhm0Ccu4fPFK069oOdu9rAr30LSqgE.jpg",
        "directViewUrl": "/vault/content/1jrBhm0Ccu4fPFK069oOdu9rAr30LSqgE.jpg"
      },
      {
        "id": "1kQGwv0_MCcV1QFYfitWRQVuIxPx2_9f8",
        "name": "car.png",
        "meta": "994 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1kQGwv0_MCcV1QFYfitWRQVuIxPx2_9f8.jpg",
        "fullUrl": "/vault/content/1kQGwv0_MCcV1QFYfitWRQVuIxPx2_9f8.jpg",
        "directViewUrl": "/vault/content/1kQGwv0_MCcV1QFYfitWRQVuIxPx2_9f8.jpg"
      },
      {
        "id": "1bMyYqr1HbzKpWMAFUE_-emgik669P5tt",
        "name": "gym.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1bMyYqr1HbzKpWMAFUE_-emgik669P5tt.jpg",
        "fullUrl": "/vault/content/1bMyYqr1HbzKpWMAFUE_-emgik669P5tt.jpg",
        "directViewUrl": "/vault/content/1bMyYqr1HbzKpWMAFUE_-emgik669P5tt.jpg"
      },
      {
        "id": "1Xjq_DR-oYhMQilqK-lv_JYzpTr7q4jW0",
        "name": "gym2.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1Xjq_DR-oYhMQilqK-lv_JYzpTr7q4jW0.jpg",
        "fullUrl": "/vault/content/1Xjq_DR-oYhMQilqK-lv_JYzpTr7q4jW0.jpg",
        "directViewUrl": "/vault/content/1Xjq_DR-oYhMQilqK-lv_JYzpTr7q4jW0.jpg"
      },
      {
        "id": "16tw9hGipnX2gKNsHZndkJwiFbiTCACdC",
        "name": "gym3.png",
        "meta": "1.3 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/16tw9hGipnX2gKNsHZndkJwiFbiTCACdC.jpg",
        "fullUrl": "/vault/content/16tw9hGipnX2gKNsHZndkJwiFbiTCACdC.jpg",
        "directViewUrl": "/vault/content/16tw9hGipnX2gKNsHZndkJwiFbiTCACdC.jpg"
      },
      {
        "id": "1sPOVzmXAN8JAjOjVFAsm9ZNKRkKi6-mt",
        "name": "image.png",
        "meta": "803 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1sPOVzmXAN8JAjOjVFAsm9ZNKRkKi6-mt.jpg",
        "fullUrl": "/vault/content/1sPOVzmXAN8JAjOjVFAsm9ZNKRkKi6-mt.jpg",
        "directViewUrl": "/vault/content/1sPOVzmXAN8JAjOjVFAsm9ZNKRkKi6-mt.jpg"
      },
      {
        "id": "1c6ypvGHP3Z7PuFKlNlK-gOB3crcnUW7x",
        "name": "image1.png",
        "meta": "1.6 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1c6ypvGHP3Z7PuFKlNlK-gOB3crcnUW7x.jpg",
        "fullUrl": "/vault/content/1c6ypvGHP3Z7PuFKlNlK-gOB3crcnUW7x.jpg",
        "directViewUrl": "/vault/content/1c6ypvGHP3Z7PuFKlNlK-gOB3crcnUW7x.jpg"
      },
      {
        "id": "1TJpXKkKE4hwwyo3dq66rDXYdNfHo0zRu",
        "name": "mirror_tease.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1TJpXKkKE4hwwyo3dq66rDXYdNfHo0zRu.jpg",
        "fullUrl": "/vault/content/1TJpXKkKE4hwwyo3dq66rDXYdNfHo0zRu.jpg",
        "directViewUrl": "/vault/content/1TJpXKkKE4hwwyo3dq66rDXYdNfHo0zRu.jpg"
      },
      {
        "id": "1JOtXwTVr6JA7xWQm3m1CiYaZGQGz0XAa",
        "name": "mirror.png",
        "meta": "2.6 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1JOtXwTVr6JA7xWQm3m1CiYaZGQGz0XAa.jpg",
        "fullUrl": "/vault/content/1JOtXwTVr6JA7xWQm3m1CiYaZGQGz0XAa.jpg",
        "directViewUrl": "/vault/content/1JOtXwTVr6JA7xWQm3m1CiYaZGQGz0XAa.jpg"
      },
      {
        "id": "1px8iFFcBOqKbJZcOWXzp-ydJRkBoh1Xu",
        "name": "nude_1.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1px8iFFcBOqKbJZcOWXzp-ydJRkBoh1Xu.jpg",
        "fullUrl": "/vault/content/1px8iFFcBOqKbJZcOWXzp-ydJRkBoh1Xu.jpg",
        "directViewUrl": "/vault/content/1px8iFFcBOqKbJZcOWXzp-ydJRkBoh1Xu.jpg"
      },
      {
        "id": "1rlx_5hZai8kjJYzgpXXdhJRJs9cVfJEh",
        "name": "nude_2.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1rlx_5hZai8kjJYzgpXXdhJRJs9cVfJEh.jpg",
        "fullUrl": "/vault/content/1rlx_5hZai8kjJYzgpXXdhJRJs9cVfJEh.jpg",
        "directViewUrl": "/vault/content/1rlx_5hZai8kjJYzgpXXdhJRJs9cVfJEh.jpg"
      },
      {
        "id": "1VBh6anOMaVbKVsdjoKf_flf31u0T2HLB",
        "name": "nude_3.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1VBh6anOMaVbKVsdjoKf_flf31u0T2HLB.jpg",
        "fullUrl": "/vault/content/1VBh6anOMaVbKVsdjoKf_flf31u0T2HLB.jpg",
        "directViewUrl": "/vault/content/1VBh6anOMaVbKVsdjoKf_flf31u0T2HLB.jpg"
      },
      {
        "id": "1vBttKWV--KdUxvRBv-SdSJ4cMGIp3Ph4",
        "name": "nude_4.png",
        "meta": "1.3 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1vBttKWV--KdUxvRBv-SdSJ4cMGIp3Ph4.jpg",
        "fullUrl": "/vault/content/1vBttKWV--KdUxvRBv-SdSJ4cMGIp3Ph4.jpg",
        "directViewUrl": "/vault/content/1vBttKWV--KdUxvRBv-SdSJ4cMGIp3Ph4.jpg"
      },
      {
        "id": "1R7dN8hygr2S5gAMycXP6qSKEjIRQ3m4r",
        "name": "outfit.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1R7dN8hygr2S5gAMycXP6qSKEjIRQ3m4r.jpg",
        "fullUrl": "/vault/content/1R7dN8hygr2S5gAMycXP6qSKEjIRQ3m4r.jpg",
        "directViewUrl": "/vault/content/1R7dN8hygr2S5gAMycXP6qSKEjIRQ3m4r.jpg"
      },
      {
        "id": "1ipAQy3XhGi1SmyJSoHS-T5Vpfab34UWi",
        "name": "outfit2.png",
        "meta": "1.3 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1ipAQy3XhGi1SmyJSoHS-T5Vpfab34UWi.jpg",
        "fullUrl": "/vault/content/1ipAQy3XhGi1SmyJSoHS-T5Vpfab34UWi.jpg",
        "directViewUrl": "/vault/content/1ipAQy3XhGi1SmyJSoHS-T5Vpfab34UWi.jpg"
      },
      {
        "id": "1uh34aRBODqh7XHsMYBVbjL86dGQv_ROD",
        "name": "outfit3.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1uh34aRBODqh7XHsMYBVbjL86dGQv_ROD.jpg",
        "fullUrl": "/vault/content/1uh34aRBODqh7XHsMYBVbjL86dGQv_ROD.jpg",
        "directViewUrl": "/vault/content/1uh34aRBODqh7XHsMYBVbjL86dGQv_ROD.jpg"
      },
      {
        "id": "10aMEXtbz--jHcOorCtV712DI3mzep8Ph",
        "name": "selfie.png",
        "meta": "1.7 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/10aMEXtbz--jHcOorCtV712DI3mzep8Ph.jpg",
        "fullUrl": "/vault/content/10aMEXtbz--jHcOorCtV712DI3mzep8Ph.jpg",
        "directViewUrl": "/vault/content/10aMEXtbz--jHcOorCtV712DI3mzep8Ph.jpg"
      },
      {
        "id": "1y1iR8KeRXakhBwmK7bdnoK7x_C5xKfbA",
        "name": "tease_1.png",
        "meta": "1 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1y1iR8KeRXakhBwmK7bdnoK7x_C5xKfbA.jpg",
        "fullUrl": "/vault/content/1y1iR8KeRXakhBwmK7bdnoK7x_C5xKfbA.jpg",
        "directViewUrl": "/vault/content/1y1iR8KeRXakhBwmK7bdnoK7x_C5xKfbA.jpg"
      }
    ]
  },
  {
    "id": "folder-khalie-01",
    "driveName": "Khalie - OF-Fansly",
    "coverKey": "khalie_of",
    "tierRequired": "silver",
    "creator": "Khalie",
    "title": "Khalie - Private VIP Stash",
    "tag": "PRIVATE STASH",
    "category": "Verified Partner Creator",
    "description": "High-demand private paywalled sets directly from Khalie.",
    "qualityNote": "Organic Creator Upload · Uncompressed",
    "mediaType": "photo",
    "driveFolderId": "1ClixpETBqQvIzMlpKy12sNDfttrPQjxW",
    "coverImage": "/vault/covers/khalie_of.jpg",
    "itemCount": "20 Photos",
    "filesCount": 20,
    "files": [
      {
        "id": "1TKbfeBvg53pLZI7pBsPEPF6rzBcohFUa",
        "name": "Khalie_01.png",
        "meta": "974 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1TKbfeBvg53pLZI7pBsPEPF6rzBcohFUa.jpg",
        "fullUrl": "/vault/content/1TKbfeBvg53pLZI7pBsPEPF6rzBcohFUa.jpg",
        "directViewUrl": "/vault/content/1TKbfeBvg53pLZI7pBsPEPF6rzBcohFUa.jpg"
      },
      {
        "id": "1DvhCPWQ8nosX4MP1dPSYsVkfE9xWLPmH",
        "name": "Khalie_02.png",
        "meta": "014 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1DvhCPWQ8nosX4MP1dPSYsVkfE9xWLPmH.jpg",
        "fullUrl": "/vault/content/1DvhCPWQ8nosX4MP1dPSYsVkfE9xWLPmH.jpg",
        "directViewUrl": "/vault/content/1DvhCPWQ8nosX4MP1dPSYsVkfE9xWLPmH.jpg"
      },
      {
        "id": "1siDED6pmEQvs94T8tVEO88ibQuuB5rd3",
        "name": "Khalie_03.png",
        "meta": "1.3 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1siDED6pmEQvs94T8tVEO88ibQuuB5rd3.jpg",
        "fullUrl": "/vault/content/1siDED6pmEQvs94T8tVEO88ibQuuB5rd3.jpg",
        "directViewUrl": "/vault/content/1siDED6pmEQvs94T8tVEO88ibQuuB5rd3.jpg"
      },
      {
        "id": "1wwvH7Ti6V2w7FU6FaszdVRwFztUb8sw6",
        "name": "Khalie_04.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1wwvH7Ti6V2w7FU6FaszdVRwFztUb8sw6.jpg",
        "fullUrl": "/vault/content/1wwvH7Ti6V2w7FU6FaszdVRwFztUb8sw6.jpg",
        "directViewUrl": "/vault/content/1wwvH7Ti6V2w7FU6FaszdVRwFztUb8sw6.jpg"
      },
      {
        "id": "1iI46sRREX-PqUy4TdQ542wGIWdwE-O9h",
        "name": "Khalie_05.png",
        "meta": "1.1 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1iI46sRREX-PqUy4TdQ542wGIWdwE-O9h.jpg",
        "fullUrl": "/vault/content/1iI46sRREX-PqUy4TdQ542wGIWdwE-O9h.jpg",
        "directViewUrl": "/vault/content/1iI46sRREX-PqUy4TdQ542wGIWdwE-O9h.jpg"
      },
      {
        "id": "1Bp5jQd6G486R0gtch8p-VD8JYZbQ6aGK",
        "name": "Khalie_06.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1Bp5jQd6G486R0gtch8p-VD8JYZbQ6aGK.jpg",
        "fullUrl": "/vault/content/1Bp5jQd6G486R0gtch8p-VD8JYZbQ6aGK.jpg",
        "directViewUrl": "/vault/content/1Bp5jQd6G486R0gtch8p-VD8JYZbQ6aGK.jpg"
      },
      {
        "id": "1VAfXiw2IIyzBUFJ3JjJs93UUv89prWRb",
        "name": "Khalie_07.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1VAfXiw2IIyzBUFJ3JjJs93UUv89prWRb.jpg",
        "fullUrl": "/vault/content/1VAfXiw2IIyzBUFJ3JjJs93UUv89prWRb.jpg",
        "directViewUrl": "/vault/content/1VAfXiw2IIyzBUFJ3JjJs93UUv89prWRb.jpg"
      },
      {
        "id": "1bvKTNOh0wq710oz7LYKMKXc-SEDSlH1G",
        "name": "Khalie_08.png",
        "meta": "655 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1bvKTNOh0wq710oz7LYKMKXc-SEDSlH1G.jpg",
        "fullUrl": "/vault/content/1bvKTNOh0wq710oz7LYKMKXc-SEDSlH1G.jpg",
        "directViewUrl": "/vault/content/1bvKTNOh0wq710oz7LYKMKXc-SEDSlH1G.jpg"
      },
      {
        "id": "1A7Af0NLRwUsNS53KnKHqH3JmbisfxmnX",
        "name": "Khalie_09.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1A7Af0NLRwUsNS53KnKHqH3JmbisfxmnX.jpg",
        "fullUrl": "/vault/content/1A7Af0NLRwUsNS53KnKHqH3JmbisfxmnX.jpg",
        "directViewUrl": "/vault/content/1A7Af0NLRwUsNS53KnKHqH3JmbisfxmnX.jpg"
      },
      {
        "id": "1t98oCAPT57IwOCpvl33rjbrJICM0xCcQ",
        "name": "Khalie_10.png",
        "meta": "636 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1t98oCAPT57IwOCpvl33rjbrJICM0xCcQ.jpg",
        "fullUrl": "/vault/content/1t98oCAPT57IwOCpvl33rjbrJICM0xCcQ.jpg",
        "directViewUrl": "/vault/content/1t98oCAPT57IwOCpvl33rjbrJICM0xCcQ.jpg"
      },
      {
        "id": "18UIm6MsyHyni4bMJ4qHjm4wDSQMm0gpC",
        "name": "Khalie_11.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/18UIm6MsyHyni4bMJ4qHjm4wDSQMm0gpC.jpg",
        "fullUrl": "/vault/content/18UIm6MsyHyni4bMJ4qHjm4wDSQMm0gpC.jpg",
        "directViewUrl": "/vault/content/18UIm6MsyHyni4bMJ4qHjm4wDSQMm0gpC.jpg"
      },
      {
        "id": "1AOZBTJTpAnuOvtw8VF7wpmVZzcAQikAE",
        "name": "Khalie_12.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1AOZBTJTpAnuOvtw8VF7wpmVZzcAQikAE.jpg",
        "fullUrl": "/vault/content/1AOZBTJTpAnuOvtw8VF7wpmVZzcAQikAE.jpg",
        "directViewUrl": "/vault/content/1AOZBTJTpAnuOvtw8VF7wpmVZzcAQikAE.jpg"
      },
      {
        "id": "12xZooLU9ndH97hfPSkmevTMJr-wrsglb",
        "name": "Khalie_13.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/12xZooLU9ndH97hfPSkmevTMJr-wrsglb.jpg",
        "fullUrl": "/vault/content/12xZooLU9ndH97hfPSkmevTMJr-wrsglb.jpg",
        "directViewUrl": "/vault/content/12xZooLU9ndH97hfPSkmevTMJr-wrsglb.jpg"
      },
      {
        "id": "1cDpKYIvq-hHMW8hFKeSqJaGCV3aWk8MY",
        "name": "Khalie_14.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1cDpKYIvq-hHMW8hFKeSqJaGCV3aWk8MY.jpg",
        "fullUrl": "/vault/content/1cDpKYIvq-hHMW8hFKeSqJaGCV3aWk8MY.jpg",
        "directViewUrl": "/vault/content/1cDpKYIvq-hHMW8hFKeSqJaGCV3aWk8MY.jpg"
      },
      {
        "id": "10mr7r53sQYPZtso-Ybj-835VnKeHl3U6",
        "name": "Khalie_15.png",
        "meta": "1.5 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/10mr7r53sQYPZtso-Ybj-835VnKeHl3U6.jpg",
        "fullUrl": "/vault/content/10mr7r53sQYPZtso-Ybj-835VnKeHl3U6.jpg",
        "directViewUrl": "/vault/content/10mr7r53sQYPZtso-Ybj-835VnKeHl3U6.jpg"
      },
      {
        "id": "1hHS4rb7dQ2_mrNeXM9zPVPIVUmKr6DrB",
        "name": "Khalie_16.png",
        "meta": "1.6 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1hHS4rb7dQ2_mrNeXM9zPVPIVUmKr6DrB.jpg",
        "fullUrl": "/vault/content/1hHS4rb7dQ2_mrNeXM9zPVPIVUmKr6DrB.jpg",
        "directViewUrl": "/vault/content/1hHS4rb7dQ2_mrNeXM9zPVPIVUmKr6DrB.jpg"
      },
      {
        "id": "11ZBFfM9qDwpB1-fw2KJV-oU51wFwS1ms",
        "name": "Khalie_17.png",
        "meta": "1.5 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/11ZBFfM9qDwpB1-fw2KJV-oU51wFwS1ms.jpg",
        "fullUrl": "/vault/content/11ZBFfM9qDwpB1-fw2KJV-oU51wFwS1ms.jpg",
        "directViewUrl": "/vault/content/11ZBFfM9qDwpB1-fw2KJV-oU51wFwS1ms.jpg"
      },
      {
        "id": "1t7iYAohCVe6Upm7JBGnrJxTwvYTfON19",
        "name": "Khalie_18.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1t7iYAohCVe6Upm7JBGnrJxTwvYTfON19.jpg",
        "fullUrl": "/vault/content/1t7iYAohCVe6Upm7JBGnrJxTwvYTfON19.jpg",
        "directViewUrl": "/vault/content/1t7iYAohCVe6Upm7JBGnrJxTwvYTfON19.jpg"
      },
      {
        "id": "1CSS0jpd9Ji5f9PU09yDhYce_c5j0c6nX",
        "name": "Khalie_19.png",
        "meta": "007 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1CSS0jpd9Ji5f9PU09yDhYce_c5j0c6nX.jpg",
        "fullUrl": "/vault/content/1CSS0jpd9Ji5f9PU09yDhYce_c5j0c6nX.jpg",
        "directViewUrl": "/vault/content/1CSS0jpd9Ji5f9PU09yDhYce_c5j0c6nX.jpg"
      },
      {
        "id": "1Ky1ZWntcuBZUShgmFNIK5XIVYWdo8YRV",
        "name": "Khalie_20.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1Ky1ZWntcuBZUShgmFNIK5XIVYWdo8YRV.jpg",
        "fullUrl": "/vault/content/1Ky1ZWntcuBZUShgmFNIK5XIVYWdo8YRV.jpg",
        "directViewUrl": "/vault/content/1Ky1ZWntcuBZUShgmFNIK5XIVYWdo8YRV.jpg"
      }
    ]
  },
  {
    "id": "folder-idkblondyna-01",
    "driveName": "Idkblondyna - fotky i videa",
    "coverKey": "idkblondyna",
    "tierRequired": "silver",
    "creator": "Idkblondyna",
    "title": "Idkblondyna - Screen & Cam Sessions",
    "tag": "CAM SESSIONS",
    "category": "Verified Partner Creator",
    "description": "Raw screen recordings and camera sessions recorded during private feeds.",
    "qualityNote": "Live Stream Capture · Raw Take",
    "mediaType": "video",
    "driveFolderId": "1pkw4Q1NXGhTbD154yT2p3bT0dMhhyOO0",
    "coverImage": "/vault/covers/idkblondyna.jpg",
    "itemCount": "14 Videos",
    "filesCount": 14,
    "files": [
      {
        "id": "1uYJ8bOkBE5GCORQ2n6Pn61SUEDKMITCi",
        "name": "bandicam 2026-02-27 20-38-42-233.mp4",
        "meta": "6.6 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1uYJ8bOkBE5GCORQ2n6Pn61SUEDKMITCi.jpg",
        "fullUrl": "/vault/content/1uYJ8bOkBE5GCORQ2n6Pn61SUEDKMITCi.jpg",
        "directViewUrl": "/vault/content/1uYJ8bOkBE5GCORQ2n6Pn61SUEDKMITCi.jpg",
        "videoUrl": "/vault/videos/1uYJ8bOkBE5GCORQ2n6Pn61SUEDKMITCi.mp4"
      },
      {
        "id": "1E3v6D8qLIDYVn-PHfPPqkkK8EDUMDZQ8",
        "name": "bandicam 2026-02-27 20-40-28-803.mp4",
        "meta": "16.2 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1E3v6D8qLIDYVn-PHfPPqkkK8EDUMDZQ8.jpg",
        "fullUrl": "/vault/content/1E3v6D8qLIDYVn-PHfPPqkkK8EDUMDZQ8.jpg",
        "directViewUrl": "/vault/content/1E3v6D8qLIDYVn-PHfPPqkkK8EDUMDZQ8.jpg",
        "videoUrl": "/vault/videos/1E3v6D8qLIDYVn-PHfPPqkkK8EDUMDZQ8.mp4"
      },
      {
        "id": "1W3KMkX85tQbftDQS0Bu5O7NxCcs45gvU",
        "name": "bandicam 2026-02-27 20-42-00-983.mp4",
        "meta": "32.5 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1W3KMkX85tQbftDQS0Bu5O7NxCcs45gvU.jpg",
        "fullUrl": "/vault/content/1W3KMkX85tQbftDQS0Bu5O7NxCcs45gvU.jpg",
        "directViewUrl": "/vault/content/1W3KMkX85tQbftDQS0Bu5O7NxCcs45gvU.jpg",
        "videoUrl": "/vault/videos/1W3KMkX85tQbftDQS0Bu5O7NxCcs45gvU.mp4"
      },
      {
        "id": "1f4Wc120KHtibANXMotlPls0xlEryMmZL",
        "name": "bandicam 2026-02-27 20-44-13-149.mp4",
        "meta": "12.8 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1f4Wc120KHtibANXMotlPls0xlEryMmZL.jpg",
        "fullUrl": "/vault/content/1f4Wc120KHtibANXMotlPls0xlEryMmZL.jpg",
        "directViewUrl": "/vault/content/1f4Wc120KHtibANXMotlPls0xlEryMmZL.jpg",
        "videoUrl": "/vault/videos/1f4Wc120KHtibANXMotlPls0xlEryMmZL.mp4"
      },
      {
        "id": "1PV8TdVNgxq_mfI8ezsya9XBGG3qLnwH9",
        "name": "bandicam 2026-02-27 20-46-17-715.mp4",
        "meta": "10.5 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1PV8TdVNgxq_mfI8ezsya9XBGG3qLnwH9.jpg",
        "fullUrl": "/vault/content/1PV8TdVNgxq_mfI8ezsya9XBGG3qLnwH9.jpg",
        "directViewUrl": "/vault/content/1PV8TdVNgxq_mfI8ezsya9XBGG3qLnwH9.jpg",
        "videoUrl": "/vault/videos/1PV8TdVNgxq_mfI8ezsya9XBGG3qLnwH9.mp4"
      },
      {
        "id": "11W-EEHv-oIPT1MaZsuSjkTIQeeA4w7_V",
        "name": "bandicam 2026-02-27 20-47-17-045.mp4",
        "meta": "68.3 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/11W-EEHv-oIPT1MaZsuSjkTIQeeA4w7_V.jpg",
        "fullUrl": "/vault/content/11W-EEHv-oIPT1MaZsuSjkTIQeeA4w7_V.jpg",
        "directViewUrl": "/vault/content/11W-EEHv-oIPT1MaZsuSjkTIQeeA4w7_V.jpg",
        "videoUrl": "/vault/videos/11W-EEHv-oIPT1MaZsuSjkTIQeeA4w7_V.mp4"
      },
      {
        "id": "1XP_0ZxVFbh9GTB7GSTFAThfntGI1xf5f",
        "name": "bandicam 2026-02-27 20-50-29-416.mp4",
        "meta": "86.3 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1XP_0ZxVFbh9GTB7GSTFAThfntGI1xf5f.jpg",
        "fullUrl": "/vault/content/1XP_0ZxVFbh9GTB7GSTFAThfntGI1xf5f.jpg",
        "directViewUrl": "/vault/content/1XP_0ZxVFbh9GTB7GSTFAThfntGI1xf5f.jpg",
        "videoUrl": "/vault/videos/1XP_0ZxVFbh9GTB7GSTFAThfntGI1xf5f.mp4"
      },
      {
        "id": "1jI_ilTpYBhTiNn1NpmsDtkgkE4phvENv",
        "name": "bandicam 2026-02-27 20-53-12-053.mp4",
        "meta": "276.4 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1jI_ilTpYBhTiNn1NpmsDtkgkE4phvENv.jpg",
        "fullUrl": "/vault/content/1jI_ilTpYBhTiNn1NpmsDtkgkE4phvENv.jpg",
        "directViewUrl": "/vault/content/1jI_ilTpYBhTiNn1NpmsDtkgkE4phvENv.jpg",
        "videoUrl": "/vault/videos/1jI_ilTpYBhTiNn1NpmsDtkgkE4phvENv.mp4"
      },
      {
        "id": "1pvctt5HIcu0eIhAAc-fYc7nR6wL7Y278",
        "name": "bandicam 2026-02-27 20-59-13-758.mp4",
        "meta": "228.2 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1pvctt5HIcu0eIhAAc-fYc7nR6wL7Y278.jpg",
        "fullUrl": "/vault/content/1pvctt5HIcu0eIhAAc-fYc7nR6wL7Y278.jpg",
        "directViewUrl": "/vault/content/1pvctt5HIcu0eIhAAc-fYc7nR6wL7Y278.jpg",
        "videoUrl": "/vault/videos/1pvctt5HIcu0eIhAAc-fYc7nR6wL7Y278.mp4"
      },
      {
        "id": "16907QiP-pR4py7Tm6Cur51iCvxGJyvoo",
        "name": "bandicam 2026-02-27 21-04-40-313.mp4",
        "meta": "356.8 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/16907QiP-pR4py7Tm6Cur51iCvxGJyvoo.jpg",
        "fullUrl": "/vault/content/16907QiP-pR4py7Tm6Cur51iCvxGJyvoo.jpg",
        "directViewUrl": "/vault/content/16907QiP-pR4py7Tm6Cur51iCvxGJyvoo.jpg",
        "videoUrl": "/vault/videos/16907QiP-pR4py7Tm6Cur51iCvxGJyvoo.mp4"
      },
      {
        "id": "1ytNqM82sDCKw-IyY1-tuGkwtR64LnSQY",
        "name": "bandicam 2026-02-27 21-10-17-768.mp4",
        "meta": "180.3 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1ytNqM82sDCKw-IyY1-tuGkwtR64LnSQY.jpg",
        "fullUrl": "/vault/content/1ytNqM82sDCKw-IyY1-tuGkwtR64LnSQY.jpg",
        "directViewUrl": "/vault/content/1ytNqM82sDCKw-IyY1-tuGkwtR64LnSQY.jpg",
        "videoUrl": "/vault/videos/1ytNqM82sDCKw-IyY1-tuGkwtR64LnSQY.mp4"
      },
      {
        "id": "1T9rX6BD6GhvTp3yWnr-Sr8nyOLZX4dSq",
        "name": "bandicam 2026-02-27 21-13-10-968.mp4",
        "meta": "17.1 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1T9rX6BD6GhvTp3yWnr-Sr8nyOLZX4dSq.jpg",
        "fullUrl": "/vault/content/1T9rX6BD6GhvTp3yWnr-Sr8nyOLZX4dSq.jpg",
        "directViewUrl": "/vault/content/1T9rX6BD6GhvTp3yWnr-Sr8nyOLZX4dSq.jpg",
        "videoUrl": "/vault/videos/1T9rX6BD6GhvTp3yWnr-Sr8nyOLZX4dSq.mp4"
      },
      {
        "id": "1N2SgWMXQHlTjGchgS52Shm3vYYn6fv1-",
        "name": "bandicam 2026-02-27 21-13-38-410.mp4",
        "meta": "11.7 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1N2SgWMXQHlTjGchgS52Shm3vYYn6fv1-.jpg",
        "fullUrl": "/vault/content/1N2SgWMXQHlTjGchgS52Shm3vYYn6fv1-.jpg",
        "directViewUrl": "/vault/content/1N2SgWMXQHlTjGchgS52Shm3vYYn6fv1-.jpg",
        "videoUrl": "/vault/videos/1N2SgWMXQHlTjGchgS52Shm3vYYn6fv1-.mp4"
      },
      {
        "id": "1mh5BqjcPhFVmta2ZMeq3DZEpIVj_ey8O",
        "name": "bandicam 2026-02-27 21-14-06-728.mp4",
        "meta": "10 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1mh5BqjcPhFVmta2ZMeq3DZEpIVj_ey8O.jpg",
        "fullUrl": "/vault/content/1mh5BqjcPhFVmta2ZMeq3DZEpIVj_ey8O.jpg",
        "directViewUrl": "/vault/content/1mh5BqjcPhFVmta2ZMeq3DZEpIVj_ey8O.jpg",
        "videoUrl": "/vault/videos/1mh5BqjcPhFVmta2ZMeq3DZEpIVj_ey8O.mp4"
      }
    ]
  },
  {
    "id": "folder-nevim-01",
    "driveName": "Nevim777 - OF-Fansly",
    "coverKey": "nevim_of",
    "tierRequired": "silver",
    "creator": "Nevim777",
    "title": "Nevim777 - VIP Vault Sets",
    "tag": "VAULT SET",
    "category": "Verified Partner Creator",
    "description": "Premium subscription albums and high-detail photos from Nevim777.",
    "qualityNote": "Original Camera Roll Resolution",
    "mediaType": "photo",
    "driveFolderId": "17pfxR4uRW4FuQ7yKg05Y8LwZxGojZRAs",
    "coverImage": "/vault/covers/nevim_of.jpg",
    "itemCount": "20 Photos",
    "filesCount": 20,
    "files": [
      {
        "id": "1lQQCtqkxJpV2mcyoFjdH4RwIoo3gSwmD",
        "name": "777 - 01.png",
        "meta": "1.3 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1lQQCtqkxJpV2mcyoFjdH4RwIoo3gSwmD.jpg",
        "fullUrl": "/vault/content/1lQQCtqkxJpV2mcyoFjdH4RwIoo3gSwmD.jpg",
        "directViewUrl": "/vault/content/1lQQCtqkxJpV2mcyoFjdH4RwIoo3gSwmD.jpg"
      },
      {
        "id": "11OMf-S7zVpNVzmlQMypS6gaWzlJ5lP29",
        "name": "777_02.png",
        "meta": "934 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/11OMf-S7zVpNVzmlQMypS6gaWzlJ5lP29.jpg",
        "fullUrl": "/vault/content/11OMf-S7zVpNVzmlQMypS6gaWzlJ5lP29.jpg",
        "directViewUrl": "/vault/content/11OMf-S7zVpNVzmlQMypS6gaWzlJ5lP29.jpg"
      },
      {
        "id": "1YfKBb5aLodvkkR8lAhC2dxTDr0nbNzAz",
        "name": "777_03.png",
        "meta": "1.6 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1YfKBb5aLodvkkR8lAhC2dxTDr0nbNzAz.jpg",
        "fullUrl": "/vault/content/1YfKBb5aLodvkkR8lAhC2dxTDr0nbNzAz.jpg",
        "directViewUrl": "/vault/content/1YfKBb5aLodvkkR8lAhC2dxTDr0nbNzAz.jpg"
      },
      {
        "id": "1OlvKvkzixL1E9DWFj4dESKP5rzpeykJD",
        "name": "777_04.png",
        "meta": "1.1 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1OlvKvkzixL1E9DWFj4dESKP5rzpeykJD.jpg",
        "fullUrl": "/vault/content/1OlvKvkzixL1E9DWFj4dESKP5rzpeykJD.jpg",
        "directViewUrl": "/vault/content/1OlvKvkzixL1E9DWFj4dESKP5rzpeykJD.jpg"
      },
      {
        "id": "148-DFyvQ4lY8PoOHJB1b-TMaDIH16mhq",
        "name": "777_05.png",
        "meta": "1.5 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/148-DFyvQ4lY8PoOHJB1b-TMaDIH16mhq.jpg",
        "fullUrl": "/vault/content/148-DFyvQ4lY8PoOHJB1b-TMaDIH16mhq.jpg",
        "directViewUrl": "/vault/content/148-DFyvQ4lY8PoOHJB1b-TMaDIH16mhq.jpg"
      },
      {
        "id": "15v5sxpJtxtjnWkFqvPncKe4QJgycCJcw",
        "name": "777_06.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/15v5sxpJtxtjnWkFqvPncKe4QJgycCJcw.jpg",
        "fullUrl": "/vault/content/15v5sxpJtxtjnWkFqvPncKe4QJgycCJcw.jpg",
        "directViewUrl": "/vault/content/15v5sxpJtxtjnWkFqvPncKe4QJgycCJcw.jpg"
      },
      {
        "id": "1ih9z6_77qvhAlMxBreNubJNGxpwsR-p2",
        "name": "777_07.png",
        "meta": "1.5 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1ih9z6_77qvhAlMxBreNubJNGxpwsR-p2.jpg",
        "fullUrl": "/vault/content/1ih9z6_77qvhAlMxBreNubJNGxpwsR-p2.jpg",
        "directViewUrl": "/vault/content/1ih9z6_77qvhAlMxBreNubJNGxpwsR-p2.jpg"
      },
      {
        "id": "1DWspV7yrSKta2Tvlo3XnlCY3fm0l98Lc",
        "name": "777_08.png",
        "meta": "1.6 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1DWspV7yrSKta2Tvlo3XnlCY3fm0l98Lc.jpg",
        "fullUrl": "/vault/content/1DWspV7yrSKta2Tvlo3XnlCY3fm0l98Lc.jpg",
        "directViewUrl": "/vault/content/1DWspV7yrSKta2Tvlo3XnlCY3fm0l98Lc.jpg"
      },
      {
        "id": "1FwMa_8t52LU1v10QUSF2P1xec9xfMDhK",
        "name": "777_09.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1FwMa_8t52LU1v10QUSF2P1xec9xfMDhK.jpg",
        "fullUrl": "/vault/content/1FwMa_8t52LU1v10QUSF2P1xec9xfMDhK.jpg",
        "directViewUrl": "/vault/content/1FwMa_8t52LU1v10QUSF2P1xec9xfMDhK.jpg"
      },
      {
        "id": "1AUxHOfHzq5oQmlgNKrmZ0gU99F5oK4Dm",
        "name": "777_10.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1AUxHOfHzq5oQmlgNKrmZ0gU99F5oK4Dm.jpg",
        "fullUrl": "/vault/content/1AUxHOfHzq5oQmlgNKrmZ0gU99F5oK4Dm.jpg",
        "directViewUrl": "/vault/content/1AUxHOfHzq5oQmlgNKrmZ0gU99F5oK4Dm.jpg"
      },
      {
        "id": "1wAifiS_LZ2ON37qOWQHu1g8-OHUv7qgm",
        "name": "777_11.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1wAifiS_LZ2ON37qOWQHu1g8-OHUv7qgm.jpg",
        "fullUrl": "/vault/content/1wAifiS_LZ2ON37qOWQHu1g8-OHUv7qgm.jpg",
        "directViewUrl": "/vault/content/1wAifiS_LZ2ON37qOWQHu1g8-OHUv7qgm.jpg"
      },
      {
        "id": "1IU3_9REreMTM4dzRb2DsDfkmQtHQrE0k",
        "name": "777_12.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1IU3_9REreMTM4dzRb2DsDfkmQtHQrE0k.jpg",
        "fullUrl": "/vault/content/1IU3_9REreMTM4dzRb2DsDfkmQtHQrE0k.jpg",
        "directViewUrl": "/vault/content/1IU3_9REreMTM4dzRb2DsDfkmQtHQrE0k.jpg"
      },
      {
        "id": "1oo59Ck7L_jasXbR9qaDp7OmPVwtugG6V",
        "name": "777_13.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1oo59Ck7L_jasXbR9qaDp7OmPVwtugG6V.jpg",
        "fullUrl": "/vault/content/1oo59Ck7L_jasXbR9qaDp7OmPVwtugG6V.jpg",
        "directViewUrl": "/vault/content/1oo59Ck7L_jasXbR9qaDp7OmPVwtugG6V.jpg"
      },
      {
        "id": "1AOfQmPYKCCyenUZFe98igYGccqTaWqnZ",
        "name": "777_14.png",
        "meta": "1.3 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1AOfQmPYKCCyenUZFe98igYGccqTaWqnZ.jpg",
        "fullUrl": "/vault/content/1AOfQmPYKCCyenUZFe98igYGccqTaWqnZ.jpg",
        "directViewUrl": "/vault/content/1AOfQmPYKCCyenUZFe98igYGccqTaWqnZ.jpg"
      },
      {
        "id": "1vI6iapER-pEXB6N97wXT1zD3BE6Hofbv",
        "name": "777_15.png",
        "meta": "1.4 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1vI6iapER-pEXB6N97wXT1zD3BE6Hofbv.jpg",
        "fullUrl": "/vault/content/1vI6iapER-pEXB6N97wXT1zD3BE6Hofbv.jpg",
        "directViewUrl": "/vault/content/1vI6iapER-pEXB6N97wXT1zD3BE6Hofbv.jpg"
      },
      {
        "id": "13iZVXWVITq7swQSgv2h-SsxrhNgtUjdI",
        "name": "777_16.png",
        "meta": "1.3 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/13iZVXWVITq7swQSgv2h-SsxrhNgtUjdI.jpg",
        "fullUrl": "/vault/content/13iZVXWVITq7swQSgv2h-SsxrhNgtUjdI.jpg",
        "directViewUrl": "/vault/content/13iZVXWVITq7swQSgv2h-SsxrhNgtUjdI.jpg"
      },
      {
        "id": "14ab8ErQp2aJl-n2safgO2iVA3eJeNN8g",
        "name": "777_17.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/14ab8ErQp2aJl-n2safgO2iVA3eJeNN8g.jpg",
        "fullUrl": "/vault/content/14ab8ErQp2aJl-n2safgO2iVA3eJeNN8g.jpg",
        "directViewUrl": "/vault/content/14ab8ErQp2aJl-n2safgO2iVA3eJeNN8g.jpg"
      },
      {
        "id": "1lBElnxcZXI16L4xxktlueM-tkIXIjKGK",
        "name": "777_18.png",
        "meta": "1.6 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1lBElnxcZXI16L4xxktlueM-tkIXIjKGK.jpg",
        "fullUrl": "/vault/content/1lBElnxcZXI16L4xxktlueM-tkIXIjKGK.jpg",
        "directViewUrl": "/vault/content/1lBElnxcZXI16L4xxktlueM-tkIXIjKGK.jpg"
      },
      {
        "id": "1QN6eAwbW4Nbt3dU6_8g_h8g7UO9TQadk",
        "name": "777_19.png",
        "meta": "1.6 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1QN6eAwbW4Nbt3dU6_8g_h8g7UO9TQadk.jpg",
        "fullUrl": "/vault/content/1QN6eAwbW4Nbt3dU6_8g_h8g7UO9TQadk.jpg",
        "directViewUrl": "/vault/content/1QN6eAwbW4Nbt3dU6_8g_h8g7UO9TQadk.jpg"
      },
      {
        "id": "1FZKPexyEjKrFJxXtTtQpf1-ZNtsWW9U8",
        "name": "777_20.png",
        "meta": "1.7 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1FZKPexyEjKrFJxXtTtQpf1-ZNtsWW9U8.jpg",
        "fullUrl": "/vault/content/1FZKPexyEjKrFJxXtTtQpf1-ZNtsWW9U8.jpg",
        "directViewUrl": "/vault/content/1FZKPexyEjKrFJxXtTtQpf1-ZNtsWW9U8.jpg"
      }
    ]
  },
  {
    "id": "folder-zoe-01",
    "driveName": "Zoe - OF-Fanvue",
    "coverKey": "zoe_of",
    "tierRequired": "silver",
    "creator": "Zoe",
    "title": "Zoe - VIP Archive Collection",
    "tag": "VIP ARCHIVE",
    "category": "Verified Partner Creator",
    "description": "Curated personal vault albums and exclusive subscriber packages from Zoe.",
    "qualityNote": "High-Res Master Photos",
    "mediaType": "photo",
    "driveFolderId": "1pDKfyOzv8Eu0znHEDf3lFyDEkRrqL2Nq",
    "coverImage": "/vault/covers/zoe_of.jpg",
    "itemCount": "17 Photos",
    "filesCount": 17,
    "files": [
      {
        "id": "1eBKRJFNVP39dWO9hOJNnceJqRN1DeOaI",
        "name": "Zoe_01.png",
        "meta": "1.6 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1eBKRJFNVP39dWO9hOJNnceJqRN1DeOaI.jpg",
        "fullUrl": "/vault/content/1eBKRJFNVP39dWO9hOJNnceJqRN1DeOaI.jpg",
        "directViewUrl": "/vault/content/1eBKRJFNVP39dWO9hOJNnceJqRN1DeOaI.jpg"
      },
      {
        "id": "1obbgqT-YFZ3w_QLXtiCzd0cA-SLSsQAd",
        "name": "Zoe_02.png",
        "meta": "1.5 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1obbgqT-YFZ3w_QLXtiCzd0cA-SLSsQAd.jpg",
        "fullUrl": "/vault/content/1obbgqT-YFZ3w_QLXtiCzd0cA-SLSsQAd.jpg",
        "directViewUrl": "/vault/content/1obbgqT-YFZ3w_QLXtiCzd0cA-SLSsQAd.jpg"
      },
      {
        "id": "1M2KzPriAY7GDsUT-HslheryCAWSepn-l",
        "name": "Zoe_03.png",
        "meta": "1.3 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1M2KzPriAY7GDsUT-HslheryCAWSepn-l.jpg",
        "fullUrl": "/vault/content/1M2KzPriAY7GDsUT-HslheryCAWSepn-l.jpg",
        "directViewUrl": "/vault/content/1M2KzPriAY7GDsUT-HslheryCAWSepn-l.jpg"
      },
      {
        "id": "1NEVBT4r5B10pdyAdLbuBoRm8fgZS2mcK",
        "name": "Zoe_04.png",
        "meta": "1.2 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1NEVBT4r5B10pdyAdLbuBoRm8fgZS2mcK.jpg",
        "fullUrl": "/vault/content/1NEVBT4r5B10pdyAdLbuBoRm8fgZS2mcK.jpg",
        "directViewUrl": "/vault/content/1NEVBT4r5B10pdyAdLbuBoRm8fgZS2mcK.jpg"
      },
      {
        "id": "1M9N9UGC1fN92i-iCXWQ-U7vGkFB9e44p",
        "name": "Zoe_05.png",
        "meta": "1.5 MB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1M9N9UGC1fN92i-iCXWQ-U7vGkFB9e44p.jpg",
        "fullUrl": "/vault/content/1M9N9UGC1fN92i-iCXWQ-U7vGkFB9e44p.jpg",
        "directViewUrl": "/vault/content/1M9N9UGC1fN92i-iCXWQ-U7vGkFB9e44p.jpg"
      },
      {
        "id": "1bd_CLqtu7Ix3feYADSY2Em6lHK6zUdAC",
        "name": "Zoe_06.png",
        "meta": "791 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1bd_CLqtu7Ix3feYADSY2Em6lHK6zUdAC.jpg",
        "fullUrl": "/vault/content/1bd_CLqtu7Ix3feYADSY2Em6lHK6zUdAC.jpg",
        "directViewUrl": "/vault/content/1bd_CLqtu7Ix3feYADSY2Em6lHK6zUdAC.jpg"
      },
      {
        "id": "1OM822cG50vVAvQC7XnPrfX8SFCv5ZLsm",
        "name": "Zoe_07.png",
        "meta": "816 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1OM822cG50vVAvQC7XnPrfX8SFCv5ZLsm.jpg",
        "fullUrl": "/vault/content/1OM822cG50vVAvQC7XnPrfX8SFCv5ZLsm.jpg",
        "directViewUrl": "/vault/content/1OM822cG50vVAvQC7XnPrfX8SFCv5ZLsm.jpg"
      },
      {
        "id": "1JGKvp32WwpDtL9SmjsQ6HRJsILaCGrTv",
        "name": "Zoe_08.png",
        "meta": "801 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1JGKvp32WwpDtL9SmjsQ6HRJsILaCGrTv.jpg",
        "fullUrl": "/vault/content/1JGKvp32WwpDtL9SmjsQ6HRJsILaCGrTv.jpg",
        "directViewUrl": "/vault/content/1JGKvp32WwpDtL9SmjsQ6HRJsILaCGrTv.jpg"
      },
      {
        "id": "1Br-VmWxKVsPdEZ39aKlL-urfU79z5hJn",
        "name": "Zoe_09.png",
        "meta": "716 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1Br-VmWxKVsPdEZ39aKlL-urfU79z5hJn.jpg",
        "fullUrl": "/vault/content/1Br-VmWxKVsPdEZ39aKlL-urfU79z5hJn.jpg",
        "directViewUrl": "/vault/content/1Br-VmWxKVsPdEZ39aKlL-urfU79z5hJn.jpg"
      },
      {
        "id": "11JNdVmOVxxEtTNXEE-YzXQgVtRV6nVcv",
        "name": "Zoe_10.png",
        "meta": "618 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/11JNdVmOVxxEtTNXEE-YzXQgVtRV6nVcv.jpg",
        "fullUrl": "/vault/content/11JNdVmOVxxEtTNXEE-YzXQgVtRV6nVcv.jpg",
        "directViewUrl": "/vault/content/11JNdVmOVxxEtTNXEE-YzXQgVtRV6nVcv.jpg"
      },
      {
        "id": "14gMZX7zyk4cfUH6wYvV5NwXCkF4YCjUh",
        "name": "Zoe_11.png",
        "meta": "666 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/14gMZX7zyk4cfUH6wYvV5NwXCkF4YCjUh.jpg",
        "fullUrl": "/vault/content/14gMZX7zyk4cfUH6wYvV5NwXCkF4YCjUh.jpg",
        "directViewUrl": "/vault/content/14gMZX7zyk4cfUH6wYvV5NwXCkF4YCjUh.jpg"
      },
      {
        "id": "1zqoFZbmQqhRaciCrhrgY4f0RNtsMArfL",
        "name": "Zoe_12.png",
        "meta": "690 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1zqoFZbmQqhRaciCrhrgY4f0RNtsMArfL.jpg",
        "fullUrl": "/vault/content/1zqoFZbmQqhRaciCrhrgY4f0RNtsMArfL.jpg",
        "directViewUrl": "/vault/content/1zqoFZbmQqhRaciCrhrgY4f0RNtsMArfL.jpg"
      },
      {
        "id": "1QxIm2CBztOr8isIDtPrAw0r7kt70JiCO",
        "name": "Zoe_13.png",
        "meta": "666 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1QxIm2CBztOr8isIDtPrAw0r7kt70JiCO.jpg",
        "fullUrl": "/vault/content/1QxIm2CBztOr8isIDtPrAw0r7kt70JiCO.jpg",
        "directViewUrl": "/vault/content/1QxIm2CBztOr8isIDtPrAw0r7kt70JiCO.jpg"
      },
      {
        "id": "1I1_SUA-FEtr5BnkFUMv6f-nRaGjYhKB1",
        "name": "Zoe_14.png",
        "meta": "717 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1I1_SUA-FEtr5BnkFUMv6f-nRaGjYhKB1.jpg",
        "fullUrl": "/vault/content/1I1_SUA-FEtr5BnkFUMv6f-nRaGjYhKB1.jpg",
        "directViewUrl": "/vault/content/1I1_SUA-FEtr5BnkFUMv6f-nRaGjYhKB1.jpg"
      },
      {
        "id": "1IcO8hi4mmnB65PnHZ-FODN2D2Lh8e2Ak",
        "name": "Zoe_15.png",
        "meta": "830 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1IcO8hi4mmnB65PnHZ-FODN2D2Lh8e2Ak.jpg",
        "fullUrl": "/vault/content/1IcO8hi4mmnB65PnHZ-FODN2D2Lh8e2Ak.jpg",
        "directViewUrl": "/vault/content/1IcO8hi4mmnB65PnHZ-FODN2D2Lh8e2Ak.jpg"
      },
      {
        "id": "12B2vj5ejiDfI0Q69_w70MN13B_nCbrB8",
        "name": "Zoe_16.png",
        "meta": "273 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/12B2vj5ejiDfI0Q69_w70MN13B_nCbrB8.jpg",
        "fullUrl": "/vault/content/12B2vj5ejiDfI0Q69_w70MN13B_nCbrB8.jpg",
        "directViewUrl": "/vault/content/12B2vj5ejiDfI0Q69_w70MN13B_nCbrB8.jpg"
      },
      {
        "id": "1UxeGmbgrRE75idiu-T23XVz9KKnl4i2s",
        "name": "Zoe_17.png",
        "meta": "796 kB · Studio Raw",
        "ext": "png",
        "type": "image",
        "thumbUrl": "/vault/content/1UxeGmbgrRE75idiu-T23XVz9KKnl4i2s.jpg",
        "fullUrl": "/vault/content/1UxeGmbgrRE75idiu-T23XVz9KKnl4i2s.jpg",
        "directViewUrl": "/vault/content/1UxeGmbgrRE75idiu-T23XVz9KKnl4i2s.jpg"
      }
    ]
  },
  {
    "id": "folder-cleo-02",
    "driveName": "Cleo - Videa - NEEDS CUT!",
    "coverKey": "cleo_videa",
    "tierRequired": "gold",
    "creator": "Cleo",
    "title": "Cleo - Raw Video Sessions (Uncut)",
    "tag": "RAW UNEDITED",
    "category": "Raw Reel Archive",
    "description": "Unfiltered mobile video takes straight from Cleo camera roll prior to final cutting.",
    "qualityNote": "Authentic Raw Take · Zero Filters",
    "mediaType": "video",
    "driveFolderId": "1vMKeQjPoBwByGQlXQRDlATy0KV4HvUVB",
    "coverImage": "/vault/covers/cleo_videa.jpg",
    "itemCount": "8 Videos",
    "filesCount": 8,
    "files": [
      {
        "id": "11pYk69DL8xI6rN27kGKdc2YTLo9_x2g_",
        "name": "Cleo - Dressing up - Tits visible - Better.mp4",
        "meta": "15.8 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/11pYk69DL8xI6rN27kGKdc2YTLo9_x2g_.jpg",
        "fullUrl": "/vault/content/11pYk69DL8xI6rN27kGKdc2YTLo9_x2g_.jpg",
        "directViewUrl": "/vault/content/11pYk69DL8xI6rN27kGKdc2YTLo9_x2g_.jpg",
        "videoUrl": "/vault/videos/11pYk69DL8xI6rN27kGKdc2YTLo9_x2g_.mp4"
      },
      {
        "id": "1Ce8QEYpa4IKPTv_wBREiKr8hsg0pBx4-",
        "name": "Cleo - Dressing up - Tits visible.mp4",
        "meta": "6.7 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1Ce8QEYpa4IKPTv_wBREiKr8hsg0pBx4-.jpg",
        "fullUrl": "/vault/content/1Ce8QEYpa4IKPTv_wBREiKr8hsg0pBx4-.jpg",
        "directViewUrl": "/vault/content/1Ce8QEYpa4IKPTv_wBREiKr8hsg0pBx4-.jpg",
        "videoUrl": "/vault/videos/1Ce8QEYpa4IKPTv_wBREiKr8hsg0pBx4-.mp4"
      },
      {
        "id": "1mc3fQ5QWCa0vt58FKYzA7MYOMSXe2Jud",
        "name": "Cleo - idk asi tease.mp4",
        "meta": "7.4 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1mc3fQ5QWCa0vt58FKYzA7MYOMSXe2Jud.jpg",
        "fullUrl": "/vault/content/1mc3fQ5QWCa0vt58FKYzA7MYOMSXe2Jud.jpg",
        "directViewUrl": "/vault/content/1mc3fQ5QWCa0vt58FKYzA7MYOMSXe2Jud.jpg",
        "videoUrl": "/vault/videos/1mc3fQ5QWCa0vt58FKYzA7MYOMSXe2Jud.mp4"
      },
      {
        "id": "10BWIvJFlq2dAd24mpUnc4M5057L2SiZH",
        "name": "Cleo - Naughty clothes - Strip.mp4",
        "meta": "9.4 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/10BWIvJFlq2dAd24mpUnc4M5057L2SiZH.jpg",
        "fullUrl": "/vault/content/10BWIvJFlq2dAd24mpUnc4M5057L2SiZH.jpg",
        "directViewUrl": "/vault/content/10BWIvJFlq2dAd24mpUnc4M5057L2SiZH.jpg",
        "videoUrl": "/vault/videos/10BWIvJFlq2dAd24mpUnc4M5057L2SiZH.mp4"
      },
      {
        "id": "1v6KwttGbY7lnIYaVxWgSOcWWAdjoRdpv",
        "name": "Cleo - On beach - Sexy?.mp4",
        "meta": "12.8 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1v6KwttGbY7lnIYaVxWgSOcWWAdjoRdpv.jpg",
        "fullUrl": "/vault/content/1v6KwttGbY7lnIYaVxWgSOcWWAdjoRdpv.jpg",
        "directViewUrl": "/vault/content/1v6KwttGbY7lnIYaVxWgSOcWWAdjoRdpv.jpg",
        "videoUrl": "/vault/videos/1v6KwttGbY7lnIYaVxWgSOcWWAdjoRdpv.mp4"
      },
      {
        "id": "1qvjZ5rULh8V1qQtxihpxp1-R0aE1dAIR",
        "name": "Cleo - Showing ass in doggy - Better.mp4",
        "meta": "3.3 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1qvjZ5rULh8V1qQtxihpxp1-R0aE1dAIR.jpg",
        "fullUrl": "/vault/content/1qvjZ5rULh8V1qQtxihpxp1-R0aE1dAIR.jpg",
        "directViewUrl": "/vault/content/1qvjZ5rULh8V1qQtxihpxp1-R0aE1dAIR.jpg",
        "videoUrl": "/vault/videos/1qvjZ5rULh8V1qQtxihpxp1-R0aE1dAIR.mp4"
      },
      {
        "id": "172lgxYoAAmBex-U3H8PEmHRp13YS1lPK",
        "name": "Cleo - Showing ass.mp4",
        "meta": "10.7 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/172lgxYoAAmBex-U3H8PEmHRp13YS1lPK.jpg",
        "fullUrl": "/vault/content/172lgxYoAAmBex-U3H8PEmHRp13YS1lPK.jpg",
        "directViewUrl": "/vault/content/172lgxYoAAmBex-U3H8PEmHRp13YS1lPK.jpg",
        "videoUrl": "/vault/videos/172lgxYoAAmBex-U3H8PEmHRp13YS1lPK.mp4"
      },
      {
        "id": "1bk-XYJVPMU9ITTOAL7iTxPvjVH6FEPpC",
        "name": "Cleo - Visible tits - Strip?.mp4",
        "meta": "9.7 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1bk-XYJVPMU9ITTOAL7iTxPvjVH6FEPpC.jpg",
        "fullUrl": "/vault/content/1bk-XYJVPMU9ITTOAL7iTxPvjVH6FEPpC.jpg",
        "directViewUrl": "/vault/content/1bk-XYJVPMU9ITTOAL7iTxPvjVH6FEPpC.jpg",
        "videoUrl": "/vault/videos/1bk-XYJVPMU9ITTOAL7iTxPvjVH6FEPpC.mp4"
      }
    ]
  },
  {
    "id": "folder-khalie-02",
    "driveName": "Khalie - Videa - NEEDS CUT!",
    "coverKey": "khalie_videa",
    "tierRequired": "gold",
    "creator": "Khalie",
    "title": "Khalie - Uncut Video Takes",
    "tag": "RAW UNEDITED",
    "category": "Raw Reel Archive",
    "description": "Full-length raw uncompressed mobile video sessions from Khalie private feed.",
    "qualityNote": "Raw Mobile Resolution",
    "mediaType": "video",
    "driveFolderId": "1SRjfDPMzaamH6KiE98yDJRpYGrf37GT7",
    "coverImage": "/vault/covers/khalie_videa.jpg",
    "itemCount": "3 Videos",
    "filesCount": 3,
    "files": [
      {
        "id": "12KglIa4-xA8SxCN4rc0hBXOL2mdfNYYR",
        "name": "Khalie - In front of mirror - Fully nude.mp4",
        "meta": "8.2 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/12KglIa4-xA8SxCN4rc0hBXOL2mdfNYYR.jpg",
        "fullUrl": "/vault/content/12KglIa4-xA8SxCN4rc0hBXOL2mdfNYYR.jpg",
        "directViewUrl": "/vault/content/12KglIa4-xA8SxCN4rc0hBXOL2mdfNYYR.jpg",
        "videoUrl": "/vault/videos/12KglIa4-xA8SxCN4rc0hBXOL2mdfNYYR.mp4"
      },
      {
        "id": "1vOFctEdCyTnSgnBMOnkQBfF0GzIzACx9",
        "name": "Khalie - Showering - Fully nude - 2.mp4",
        "meta": "19.1 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1vOFctEdCyTnSgnBMOnkQBfF0GzIzACx9.jpg",
        "fullUrl": "/vault/content/1vOFctEdCyTnSgnBMOnkQBfF0GzIzACx9.jpg",
        "directViewUrl": "/vault/content/1vOFctEdCyTnSgnBMOnkQBfF0GzIzACx9.jpg",
        "videoUrl": "/vault/videos/1vOFctEdCyTnSgnBMOnkQBfF0GzIzACx9.mp4"
      },
      {
        "id": "1Dp7OaY7v8pMvehw1M4dUaJPm_dEWG-jx",
        "name": "Khalie - Showering - Fully nude.mp4",
        "meta": "56.9 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1Dp7OaY7v8pMvehw1M4dUaJPm_dEWG-jx.jpg",
        "fullUrl": "/vault/content/1Dp7OaY7v8pMvehw1M4dUaJPm_dEWG-jx.jpg",
        "directViewUrl": "/vault/content/1Dp7OaY7v8pMvehw1M4dUaJPm_dEWG-jx.jpg",
        "videoUrl": "/vault/videos/1Dp7OaY7v8pMvehw1M4dUaJPm_dEWG-jx.mp4"
      }
    ]
  },
  {
    "id": "folder-melissa-02",
    "driveName": "Melissa - Videa",
    "coverKey": "melissa_videa",
    "tierRequired": "gold",
    "creator": "Melissa",
    "title": "Melissa - Private Video Reels",
    "tag": "EXCLUSIVE REELS",
    "category": "Video Vault",
    "description": "Private subscriber video reels and unreleased video cuts from Melissa.",
    "qualityNote": "Direct Camera Export",
    "mediaType": "video",
    "driveFolderId": "17njwbjL1ttdOIcXumhlQSHz1lre6BBoD",
    "coverImage": "/vault/covers/melissa_videa.jpg",
    "itemCount": "12 Videos",
    "filesCount": 12,
    "files": [
      {
        "id": "1FUgXWqvZRhT32Av232BvWCDvyS76C8jb",
        "name": "Kamryn - Bra + sundavani-vanocnich-teplaku.mp4",
        "meta": "12.4 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1FUgXWqvZRhT32Av232BvWCDvyS76C8jb.jpg",
        "fullUrl": "/vault/content/1FUgXWqvZRhT32Av232BvWCDvyS76C8jb.jpg",
        "directViewUrl": "/vault/content/1FUgXWqvZRhT32Av232BvWCDvyS76C8jb.jpg",
        "videoUrl": "/vault/videos/1FUgXWqvZRhT32Av232BvWCDvyS76C8jb.mp4"
      },
      {
        "id": "1nhyU-nD7T8viZnBp--ozz45O-ZwtxB9a",
        "name": "Kamryn - Mackani cecku - fully nude.mp4",
        "meta": "23 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1nhyU-nD7T8viZnBp--ozz45O-ZwtxB9a.jpg",
        "fullUrl": "/vault/content/1nhyU-nD7T8viZnBp--ozz45O-ZwtxB9a.jpg",
        "directViewUrl": "/vault/content/1nhyU-nD7T8viZnBp--ozz45O-ZwtxB9a.jpg",
        "videoUrl": "/vault/videos/1nhyU-nD7T8viZnBp--ozz45O-ZwtxB9a.mp4"
      },
      {
        "id": "1PC6NDp027VttfxRmAWYe3o4aHWv28Wgq",
        "name": "Kamryn - Mackani cecku + Nike pros.mp4",
        "meta": "60.6 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1PC6NDp027VttfxRmAWYe3o4aHWv28Wgq.jpg",
        "fullUrl": "/vault/content/1PC6NDp027VttfxRmAWYe3o4aHWv28Wgq.jpg",
        "directViewUrl": "/vault/content/1PC6NDp027VttfxRmAWYe3o4aHWv28Wgq.jpg",
        "videoUrl": "/vault/videos/1PC6NDp027VttfxRmAWYe3o4aHWv28Wgq.mp4"
      },
      {
        "id": "1_KgA75AOa9EnWHMl51AiCdxIJseKNsvM",
        "name": "Kamryn - Oblikani se- Getting ready for the day.mp4",
        "meta": "119 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1_KgA75AOa9EnWHMl51AiCdxIJseKNsvM.jpg",
        "fullUrl": "/vault/content/1_KgA75AOa9EnWHMl51AiCdxIJseKNsvM.jpg",
        "directViewUrl": "/vault/content/1_KgA75AOa9EnWHMl51AiCdxIJseKNsvM.jpg",
        "videoUrl": "/vault/videos/1_KgA75AOa9EnWHMl51AiCdxIJseKNsvM.mp4"
      },
      {
        "id": "14ljGXSdrcdm5cMERx-5piASFaZ9DQGgU",
        "name": "Kamryn - Rozepínání košile.mp4",
        "meta": "118.3 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/14ljGXSdrcdm5cMERx-5piASFaZ9DQGgU.jpg",
        "fullUrl": "/vault/content/14ljGXSdrcdm5cMERx-5piASFaZ9DQGgU.jpg",
        "directViewUrl": "/vault/content/14ljGXSdrcdm5cMERx-5piASFaZ9DQGgU.jpg",
        "videoUrl": "/vault/videos/14ljGXSdrcdm5cMERx-5piASFaZ9DQGgU.mp4"
      },
      {
        "id": "1TFgEZ6I12SilTvBmEqsWLNt02g25a6x6",
        "name": "Kamryn - Rozepínání mikiny.mp4",
        "meta": "14.6 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1TFgEZ6I12SilTvBmEqsWLNt02g25a6x6.jpg",
        "fullUrl": "/vault/content/1TFgEZ6I12SilTvBmEqsWLNt02g25a6x6.jpg",
        "directViewUrl": "/vault/content/1TFgEZ6I12SilTvBmEqsWLNt02g25a6x6.jpg",
        "videoUrl": "/vault/videos/1TFgEZ6I12SilTvBmEqsWLNt02g25a6x6.mp4"
      },
      {
        "id": "14-aSz-QG1xaajJTW0muPMhJ1EErctcvz",
        "name": "Kamryn? - Bra + sundavani-vanocnich-teplaku.mp4",
        "meta": "2.2 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/14-aSz-QG1xaajJTW0muPMhJ1EErctcvz.jpg",
        "fullUrl": "/vault/content/14-aSz-QG1xaajJTW0muPMhJ1EErctcvz.jpg",
        "directViewUrl": "/vault/content/14-aSz-QG1xaajJTW0muPMhJ1EErctcvz.jpg",
        "videoUrl": "/vault/videos/14-aSz-QG1xaajJTW0muPMhJ1EErctcvz.mp4"
      },
      {
        "id": "1hr-WSeMgFxXKQ9ZBGh9EN9vTeKdNxYOC",
        "name": "Kamryn? - Mackani cecku - fully nude.mp4",
        "meta": "4.2 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1hr-WSeMgFxXKQ9ZBGh9EN9vTeKdNxYOC.jpg",
        "fullUrl": "/vault/content/1hr-WSeMgFxXKQ9ZBGh9EN9vTeKdNxYOC.jpg",
        "directViewUrl": "/vault/content/1hr-WSeMgFxXKQ9ZBGh9EN9vTeKdNxYOC.jpg",
        "videoUrl": "/vault/videos/1hr-WSeMgFxXKQ9ZBGh9EN9vTeKdNxYOC.mp4"
      },
      {
        "id": "10qvyV82n69FhMA_hwJTVlgg8yAMfvAJd",
        "name": "Kamryn? - Mackani cecku + Nike pros.mp4",
        "meta": "12.3 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/10qvyV82n69FhMA_hwJTVlgg8yAMfvAJd.jpg",
        "fullUrl": "/vault/content/10qvyV82n69FhMA_hwJTVlgg8yAMfvAJd.jpg",
        "directViewUrl": "/vault/content/10qvyV82n69FhMA_hwJTVlgg8yAMfvAJd.jpg",
        "videoUrl": "/vault/videos/10qvyV82n69FhMA_hwJTVlgg8yAMfvAJd.mp4"
      },
      {
        "id": "1ihdXg0BSpmvVeIx3Cp5o61nbKFY5RG9N",
        "name": "Kamryn? - Oblikani se- Getting ready for the day.mp4",
        "meta": "19.5 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1ihdXg0BSpmvVeIx3Cp5o61nbKFY5RG9N.jpg",
        "fullUrl": "/vault/content/1ihdXg0BSpmvVeIx3Cp5o61nbKFY5RG9N.jpg",
        "directViewUrl": "/vault/content/1ihdXg0BSpmvVeIx3Cp5o61nbKFY5RG9N.jpg",
        "videoUrl": "/vault/videos/1ihdXg0BSpmvVeIx3Cp5o61nbKFY5RG9N.mp4"
      },
      {
        "id": "10Kk9QI3UBrGfrBsGCmaGtaxuHfsa-QWb",
        "name": "Kamryn? - Rozepínání košile.mp4",
        "meta": "14.7 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/10Kk9QI3UBrGfrBsGCmaGtaxuHfsa-QWb.jpg",
        "fullUrl": "/vault/content/10Kk9QI3UBrGfrBsGCmaGtaxuHfsa-QWb.jpg",
        "directViewUrl": "/vault/content/10Kk9QI3UBrGfrBsGCmaGtaxuHfsa-QWb.jpg",
        "videoUrl": "/vault/videos/10Kk9QI3UBrGfrBsGCmaGtaxuHfsa-QWb.mp4"
      },
      {
        "id": "1F5QoQQSglqQfUVEK0udW5BiEVsyoZf_U",
        "name": "Kamryn? - Rozepínání mikiny.mp4",
        "meta": "2.2 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1F5QoQQSglqQfUVEK0udW5BiEVsyoZf_U.jpg",
        "fullUrl": "/vault/content/1F5QoQQSglqQfUVEK0udW5BiEVsyoZf_U.jpg",
        "directViewUrl": "/vault/content/1F5QoQQSglqQfUVEK0udW5BiEVsyoZf_U.jpg",
        "videoUrl": "/vault/videos/1F5QoQQSglqQfUVEK0udW5BiEVsyoZf_U.mp4"
      }
    ]
  },
  {
    "id": "folder-nevim-02",
    "driveName": "Nevim777 - Videa - NEEDS CUT!",
    "coverKey": "nevim_videa",
    "tierRequired": "gold",
    "creator": "Nevim777",
    "title": "Nevim777 - Uncut Video Chronicle",
    "tag": "RAW UNEDITED",
    "category": "Raw Reel Archive",
    "description": "Spontaneous uncut camera recordings and raw mobile video files from Nevim777.",
    "qualityNote": "Natural Camera Resolution",
    "mediaType": "video",
    "driveFolderId": "1iDdqAL3pPND9OrOFuAhj1h9QjwaPeHH_",
    "coverImage": "/vault/covers/nevim_videa.jpg",
    "itemCount": "7 Videos",
    "filesCount": 7,
    "files": [
      {
        "id": "1FnSuqa2IRdsfUkZQo_Uzs1XT4az3XvPG",
        "name": "Josie - Dildo - fully nude.mp4",
        "meta": "11.1 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1FnSuqa2IRdsfUkZQo_Uzs1XT4az3XvPG.jpg",
        "fullUrl": "/vault/content/1FnSuqa2IRdsfUkZQo_Uzs1XT4az3XvPG.jpg",
        "directViewUrl": "/vault/content/1FnSuqa2IRdsfUkZQo_Uzs1XT4az3XvPG.jpg",
        "videoUrl": "/vault/videos/1FnSuqa2IRdsfUkZQo_Uzs1XT4az3XvPG.mp4"
      },
      {
        "id": "1zUXyK1WsVkxqOKCsi6EIsW3gyMePHYyL",
        "name": "Josie - Dildo - Nejlepsi.mp4",
        "meta": "13 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1zUXyK1WsVkxqOKCsi6EIsW3gyMePHYyL.jpg",
        "fullUrl": "/vault/content/1zUXyK1WsVkxqOKCsi6EIsW3gyMePHYyL.jpg",
        "directViewUrl": "/vault/content/1zUXyK1WsVkxqOKCsi6EIsW3gyMePHYyL.jpg",
        "videoUrl": "/vault/videos/1zUXyK1WsVkxqOKCsi6EIsW3gyMePHYyL.mp4"
      },
      {
        "id": "1ggJTC-H_bkjMRWWDT3ptBkUeaqYl9Tl4",
        "name": "Josie - Dildo - Pokracovani-2(kratky).mp4",
        "meta": "510 kB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1ggJTC-H_bkjMRWWDT3ptBkUeaqYl9Tl4.jpg",
        "fullUrl": "/vault/content/1ggJTC-H_bkjMRWWDT3ptBkUeaqYl9Tl4.jpg",
        "directViewUrl": "/vault/content/1ggJTC-H_bkjMRWWDT3ptBkUeaqYl9Tl4.jpg",
        "videoUrl": "/vault/videos/1ggJTC-H_bkjMRWWDT3ptBkUeaqYl9Tl4.mp4"
      },
      {
        "id": "1D6YwSO8tSTRmmL5YMa8UldB1m9PUtuyA",
        "name": "Josie - Dildo - Pokracovani.mp4",
        "meta": "13.7 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1D6YwSO8tSTRmmL5YMa8UldB1m9PUtuyA.jpg",
        "fullUrl": "/vault/content/1D6YwSO8tSTRmmL5YMa8UldB1m9PUtuyA.jpg",
        "directViewUrl": "/vault/content/1D6YwSO8tSTRmmL5YMa8UldB1m9PUtuyA.jpg",
        "videoUrl": "/vault/videos/1D6YwSO8tSTRmmL5YMa8UldB1m9PUtuyA.mp4"
      },
      {
        "id": "1-SeXOZYyz-gkCeQUL2ahRbwfZJq8Z58P",
        "name": "Josie - Pussy play - fingers w a skirt/dress.mp4",
        "meta": "4.9 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1-SeXOZYyz-gkCeQUL2ahRbwfZJq8Z58P.jpg",
        "fullUrl": "/vault/content/1-SeXOZYyz-gkCeQUL2ahRbwfZJq8Z58P.jpg",
        "directViewUrl": "/vault/content/1-SeXOZYyz-gkCeQUL2ahRbwfZJq8Z58P.jpg",
        "videoUrl": "/vault/videos/1-SeXOZYyz-gkCeQUL2ahRbwfZJq8Z58P.mp4"
      },
      {
        "id": "1FO16xJZpn0zFY5HTpKu34jHopAT4qlYs",
        "name": "Josie - Showing ass and pussy - idk watch it.mp4",
        "meta": "10.4 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1FO16xJZpn0zFY5HTpKu34jHopAT4qlYs.jpg",
        "fullUrl": "/vault/content/1FO16xJZpn0zFY5HTpKu34jHopAT4qlYs.jpg",
        "directViewUrl": "/vault/content/1FO16xJZpn0zFY5HTpKu34jHopAT4qlYs.jpg",
        "videoUrl": "/vault/videos/1FO16xJZpn0zFY5HTpKu34jHopAT4qlYs.mp4"
      },
      {
        "id": "1-lV4iD88QPoNM71chVY58ftP_Xfrue4b",
        "name": "Josie - Twerking - can be used for livebait.mp4",
        "meta": "13.7 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1-lV4iD88QPoNM71chVY58ftP_Xfrue4b.jpg",
        "fullUrl": "/vault/content/1-lV4iD88QPoNM71chVY58ftP_Xfrue4b.jpg",
        "directViewUrl": "/vault/content/1-lV4iD88QPoNM71chVY58ftP_Xfrue4b.jpg",
        "videoUrl": "/vault/videos/1-lV4iD88QPoNM71chVY58ftP_Xfrue4b.mp4"
      }
    ]
  },
  {
    "id": "folder-tessa-02",
    "driveName": "Tessa - Videa - NEEDS CUT!",
    "coverKey": "tessa_videa",
    "tierRequired": "gold",
    "creator": "Tessa",
    "title": "Tessa - Uncut Video Stream",
    "tag": "RAW UNEDITED",
    "category": "Raw Reel Archive",
    "description": "Uncut video material and natural takes straight from the camera roll.",
    "qualityNote": "Organic Raw Resolution",
    "mediaType": "video",
    "driveFolderId": "1iKqP09Tykq9R_MnBG3K4Z9I2Wr31c_S8",
    "coverImage": "/vault/covers/tessa_videa.jpg",
    "itemCount": "4 Videos",
    "filesCount": 4,
    "files": [
      {
        "id": "17xEJIKbcO6qPfHC1NLfsNNrHauAXQJq5",
        "name": "Tessa - bodíčko - Better.mp4",
        "meta": "33.8 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/17xEJIKbcO6qPfHC1NLfsNNrHauAXQJq5.jpg",
        "fullUrl": "/vault/content/17xEJIKbcO6qPfHC1NLfsNNrHauAXQJq5.jpg",
        "directViewUrl": "/vault/content/17xEJIKbcO6qPfHC1NLfsNNrHauAXQJq5.jpg",
        "videoUrl": "/vault/videos/17xEJIKbcO6qPfHC1NLfsNNrHauAXQJq5.mp4"
      },
      {
        "id": "1Aj_hkncIrC_sw2Je18Q2xP5f6w19SbbL",
        "name": "Tessa - bodíčko.mp4",
        "meta": "27.6 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1Aj_hkncIrC_sw2Je18Q2xP5f6w19SbbL.jpg",
        "fullUrl": "/vault/content/1Aj_hkncIrC_sw2Je18Q2xP5f6w19SbbL.jpg",
        "directViewUrl": "/vault/content/1Aj_hkncIrC_sw2Je18Q2xP5f6w19SbbL.jpg",
        "videoUrl": "/vault/videos/1Aj_hkncIrC_sw2Je18Q2xP5f6w19SbbL.mp4"
      },
      {
        "id": "15IzXEP35AUo2IkA5NiEYjJMzzUwNIHgB",
        "name": "Tessa - Costume - na hovno.mp4",
        "meta": "1.6 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/15IzXEP35AUo2IkA5NiEYjJMzzUwNIHgB.jpg",
        "fullUrl": "/vault/content/15IzXEP35AUo2IkA5NiEYjJMzzUwNIHgB.jpg",
        "directViewUrl": "/vault/content/15IzXEP35AUo2IkA5NiEYjJMzzUwNIHgB.jpg",
        "videoUrl": "/vault/videos/15IzXEP35AUo2IkA5NiEYjJMzzUwNIHgB.mp4"
      },
      {
        "id": "1ql_FoiGi0IjSbthNewVYMCfQNRyJbXMn",
        "name": "Tessa - In front of mirror - na hovno.mp4",
        "meta": "2.3 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1ql_FoiGi0IjSbthNewVYMCfQNRyJbXMn.jpg",
        "fullUrl": "/vault/content/1ql_FoiGi0IjSbthNewVYMCfQNRyJbXMn.jpg",
        "directViewUrl": "/vault/content/1ql_FoiGi0IjSbthNewVYMCfQNRyJbXMn.jpg",
        "videoUrl": "/vault/videos/1ql_FoiGi0IjSbthNewVYMCfQNRyJbXMn.mp4"
      }
    ]
  },
  {
    "id": "folder-zoe-02",
    "driveName": "Zoe - Videa - NEEDS CUT!",
    "coverKey": "zoe_videa",
    "tierRequired": "gold",
    "creator": "Zoe",
    "title": "Zoe - Uncut Raw Recordings",
    "tag": "RAW UNEDITED",
    "category": "Raw Reel Archive",
    "description": "Spontaneous unedited camera reels directly from Zoe private storage.",
    "qualityNote": "Raw Unmastered Capture",
    "mediaType": "video",
    "driveFolderId": "10EA7mkEKvvVbMrSf6l8McmCnuIyhr9ed",
    "coverImage": "/vault/covers/zoe_videa.jpg",
    "itemCount": "4 Videos",
    "filesCount": 4,
    "files": [
      {
        "id": "1v7VHJViKSvDoXpeJBf-DqBKZU4XBoFFn",
        "name": "Zoe - BJ - Short.mp4",
        "meta": "19.9 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1v7VHJViKSvDoXpeJBf-DqBKZU4XBoFFn.jpg",
        "fullUrl": "/vault/content/1v7VHJViKSvDoXpeJBf-DqBKZU4XBoFFn.jpg",
        "directViewUrl": "/vault/content/1v7VHJViKSvDoXpeJBf-DqBKZU4XBoFFn.jpg",
        "videoUrl": "/vault/videos/1v7VHJViKSvDoXpeJBf-DqBKZU4XBoFFn.mp4"
      },
      {
        "id": "1LU7wOEZ7hXpbZ3oEQNgPdPsBY0HlEwFO",
        "name": "Zoe - Playing w pussy - short.mp4",
        "meta": "856 kB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1LU7wOEZ7hXpbZ3oEQNgPdPsBY0HlEwFO.jpg",
        "fullUrl": "/vault/content/1LU7wOEZ7hXpbZ3oEQNgPdPsBY0HlEwFO.jpg",
        "directViewUrl": "/vault/content/1LU7wOEZ7hXpbZ3oEQNgPdPsBY0HlEwFO.jpg",
        "videoUrl": "/vault/videos/1LU7wOEZ7hXpbZ3oEQNgPdPsBY0HlEwFO.mp4"
      },
      {
        "id": "12qGUcFso1nEUn2c6bPhblNklZ9cjYj0s",
        "name": "Zoe - Sextape - missionary.mp4",
        "meta": "12 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/12qGUcFso1nEUn2c6bPhblNklZ9cjYj0s.jpg",
        "fullUrl": "/vault/content/12qGUcFso1nEUn2c6bPhblNklZ9cjYj0s.jpg",
        "directViewUrl": "/vault/content/12qGUcFso1nEUn2c6bPhblNklZ9cjYj0s.jpg",
        "videoUrl": "/vault/videos/12qGUcFso1nEUn2c6bPhblNklZ9cjYj0s.mp4"
      },
      {
        "id": "1xGA-QZILO9mw49s2AHa4Ob678SWSCzeQ",
        "name": "Zoe(makeup) - Stripping + Playing w pussy - Fingering .mp4",
        "meta": "55.6 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1xGA-QZILO9mw49s2AHa4Ob678SWSCzeQ.jpg",
        "fullUrl": "/vault/content/1xGA-QZILO9mw49s2AHa4Ob678SWSCzeQ.jpg",
        "directViewUrl": "/vault/content/1xGA-QZILO9mw49s2AHa4Ob678SWSCzeQ.jpg",
        "videoUrl": "/vault/videos/1xGA-QZILO9mw49s2AHa4Ob678SWSCzeQ.mp4"
      }
    ]
  },
  {
    "id": "folder-voice-notes",
    "driveName": "Voice notes",
    "coverKey": "voice_notes",
    "tierRequired": "gold",
    "creator": "Studio Syndicate",
    "title": "Private Studio Voice Notes & Audio",
    "tag": "AUDIO INTERCEPTS",
    "category": "Behind-The-Scenes",
    "description": "Unfiltered private voice notes, green-room conversations, and creator discussions.",
    "qualityNote": "Lossless Voice Memos",
    "mediaType": "audio",
    "driveFolderId": "1bQ-Uo8bW0YLoogRJWWD5KGJr_uDvBZV0",
    "coverImage": "/vault/covers/voice_notes.jpg",
    "itemCount": "6 Voice Memos",
    "filesCount": 6,
    "files": [
      {
        "id": "1NFXItM2kaXjBdd8oDkNoEnZi204Q0gDV",
        "name": "All-my-plans-tonight-have-been-cancelled-wanna-be-here-w-me.mp4",
        "meta": "257 kB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1NFXItM2kaXjBdd8oDkNoEnZi204Q0gDV.jpg",
        "fullUrl": "/vault/content/1NFXItM2kaXjBdd8oDkNoEnZi204Q0gDV.jpg",
        "directViewUrl": "/vault/content/1NFXItM2kaXjBdd8oDkNoEnZi204Q0gDV.jpg",
        "videoUrl": "/vault/videos/1NFXItM2kaXjBdd8oDkNoEnZi204Q0gDV.mp4"
      },
      {
        "id": "1L1oERwWySUxulOk-dpwIVaaIJMToOG_-",
        "name": "Hey-I-just-wanted-to-ask-how-u-doin.mp4",
        "meta": "169 kB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1L1oERwWySUxulOk-dpwIVaaIJMToOG_-.jpg",
        "fullUrl": "/vault/content/1L1oERwWySUxulOk-dpwIVaaIJMToOG_-.jpg",
        "directViewUrl": "/vault/content/1L1oERwWySUxulOk-dpwIVaaIJMToOG_-.jpg",
        "videoUrl": "/vault/videos/1L1oERwWySUxulOk-dpwIVaaIJMToOG_-.mp4"
      },
      {
        "id": "15zcpUiWheODnaMQCOT-UHieWIpZ5BXIX",
        "name": "I-love-you-baby.mp4",
        "meta": "142 kB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/15zcpUiWheODnaMQCOT-UHieWIpZ5BXIX.jpg",
        "fullUrl": "/vault/content/15zcpUiWheODnaMQCOT-UHieWIpZ5BXIX.jpg",
        "directViewUrl": "/vault/content/15zcpUiWheODnaMQCOT-UHieWIpZ5BXIX.jpg",
        "videoUrl": "/vault/videos/15zcpUiWheODnaMQCOT-UHieWIpZ5BXIX.mp4"
      },
      {
        "id": "11Yqac-QOE8VREFgH_Xla4M2RG2sS_fw2",
        "name": "I-love-you-so-much.mp4",
        "meta": "151 kB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/11Yqac-QOE8VREFgH_Xla4M2RG2sS_fw2.jpg",
        "fullUrl": "/vault/content/11Yqac-QOE8VREFgH_Xla4M2RG2sS_fw2.jpg",
        "directViewUrl": "/vault/content/11Yqac-QOE8VREFgH_Xla4M2RG2sS_fw2.jpg",
        "videoUrl": "/vault/videos/11Yqac-QOE8VREFgH_Xla4M2RG2sS_fw2.mp4"
      },
      {
        "id": "1ejCbl5IQL1wLxAcPoNHpnIWsXuGyNF2w",
        "name": "I-will-make-you-a-spicy-video-only-for-u.mp4",
        "meta": "207 kB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1ejCbl5IQL1wLxAcPoNHpnIWsXuGyNF2w.jpg",
        "fullUrl": "/vault/content/1ejCbl5IQL1wLxAcPoNHpnIWsXuGyNF2w.jpg",
        "directViewUrl": "/vault/content/1ejCbl5IQL1wLxAcPoNHpnIWsXuGyNF2w.jpg",
        "videoUrl": "/vault/videos/1ejCbl5IQL1wLxAcPoNHpnIWsXuGyNF2w.mp4"
      },
      {
        "id": "1FYTzPAltJxILmBPuardhC7qG6Dpdgg0G",
        "name": "Its-me-Kamryn.mp4",
        "meta": "171 kB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1FYTzPAltJxILmBPuardhC7qG6Dpdgg0G.jpg",
        "fullUrl": "/vault/content/1FYTzPAltJxILmBPuardhC7qG6Dpdgg0G.jpg",
        "directViewUrl": "/vault/content/1FYTzPAltJxILmBPuardhC7qG6Dpdgg0G.jpg",
        "videoUrl": "/vault/videos/1FYTzPAltJxILmBPuardhC7qG6Dpdgg0G.mp4"
      }
    ]
  },
  {
    "id": "folder-unidentified",
    "driveName": "Neidentifikováno - videa a fotky - NEEDS CUT!",
    "coverKey": "unidentified",
    "tierRequired": "gold",
    "creator": "Classified Collab",
    "title": "Classified Session - Unidentified Vault Roll",
    "tag": "CLASSIFIED SESSION",
    "category": "Classified Drop",
    "description": "Classified studio session archive currently being cataloged for upcoming launchpad drops.",
    "qualityNote": "Raw Session Takes",
    "mediaType": "video",
    "driveFolderId": "1OPcFxi43IWjUHpL4LjM-S9-3XBOpx9TO",
    "coverImage": "/vault/covers/unidentified.jpg",
    "itemCount": "4 Videos",
    "filesCount": 4,
    "files": [
      {
        "id": "1GeDEIluCRkoIMG9cxYBcU0TxCHKz_Rz6",
        "name": "NEIDENTIFIKOVÁNO(ZJISTIT) - Dickrate - Negativní .mp4",
        "meta": "11.5 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1GeDEIluCRkoIMG9cxYBcU0TxCHKz_Rz6.jpg",
        "fullUrl": "/vault/content/1GeDEIluCRkoIMG9cxYBcU0TxCHKz_Rz6.jpg",
        "directViewUrl": "/vault/content/1GeDEIluCRkoIMG9cxYBcU0TxCHKz_Rz6.jpg",
        "videoUrl": "/vault/videos/1GeDEIluCRkoIMG9cxYBcU0TxCHKz_Rz6.mp4"
      },
      {
        "id": "1isqQlEx9my6YGKPJUYKFtc1r3fNJLI8g",
        "name": "NEIDENTIFIKOVÁNO(ZJISTIT) - Dickrate - Pozitivní.mp4",
        "meta": "17.4 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1isqQlEx9my6YGKPJUYKFtc1r3fNJLI8g.jpg",
        "fullUrl": "/vault/content/1isqQlEx9my6YGKPJUYKFtc1r3fNJLI8g.jpg",
        "directViewUrl": "/vault/content/1isqQlEx9my6YGKPJUYKFtc1r3fNJLI8g.jpg",
        "videoUrl": "/vault/videos/1isqQlEx9my6YGKPJUYKFtc1r3fNJLI8g.mp4"
      },
      {
        "id": "1C2uu8cz9hBg-cVjGvwOknYJZKJj4RA2v",
        "name": "Univerzální - nohy.mp4",
        "meta": "3.5 MB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1C2uu8cz9hBg-cVjGvwOknYJZKJj4RA2v.jpg",
        "fullUrl": "/vault/content/1C2uu8cz9hBg-cVjGvwOknYJZKJj4RA2v.jpg",
        "directViewUrl": "/vault/content/1C2uu8cz9hBg-cVjGvwOknYJZKJj4RA2v.jpg",
        "videoUrl": "/vault/videos/1C2uu8cz9hBg-cVjGvwOknYJZKJj4RA2v.mp4"
      },
      {
        "id": "1SwjLbYqbNFQf7h1M6hEHTCm_fyYGo-ag",
        "name": "Univerzalní - teasing pod kratasama.mp4",
        "meta": "819 kB · Studio Raw",
        "ext": "mp4",
        "type": "video",
        "thumbUrl": "/vault/content/1SwjLbYqbNFQf7h1M6hEHTCm_fyYGo-ag.jpg",
        "fullUrl": "/vault/content/1SwjLbYqbNFQf7h1M6hEHTCm_fyYGo-ag.jpg",
        "directViewUrl": "/vault/content/1SwjLbYqbNFQf7h1M6hEHTCm_fyYGo-ag.jpg",
        "videoUrl": "/vault/videos/1SwjLbYqbNFQf7h1M6hEHTCm_fyYGo-ag.mp4"
      }
    ]
  }
];
