// Centralized configuration and content for Ms Juicy P's SCM launch on Robinhood Chain L2

export const JUICY_CONFIG = {
  name: "Ms Juicy P",
  title: "The Vice City SCM Syndicate",
  ticker: "$JUICY",
  ca: "0x7a82B9311685Ef5832E504f2C99f3630f5A91fA0",
  network: "Robinhood Chain L2",
  symbol: "JUICY",
  decimals: 18,
  totalSupply: 1000000000,
  initialSupplyFormatted: "1,000,000,000",
  launchDateUtc: "Friday, Sep 11, 2026 · 5:00 PM UTC",
  targetTimestamp: new Date("2026-09-11T17:00:00Z").getTime(),
  xHandle: "@msjuicy_plenty",
  xUrl: "https://x.com/msjuicy_plenty",
  xFollowers: "80K+ on X",
  repostUrl: "https://x.com/mikaylafun/status/2098092424337711392?s=20",
  partnerHandle: "@CyreneAI",
  partnerUrl: "https://x.com/CyreneAI",
  dexPairUrl: "https://dexscreener.com/search?q=0x7a82B9311685Ef5832E504f2C99f3630f5A91fA0",
  explorerUrl: "https://robinhoodchain.blockscout.com/address/0x7a82B9311685Ef5832E504f2C99f3630f5A91fA0",
  burnAddress: "0x000000000000000000000000000000000000dEaD",
  graduationThresholdEth: 4.2,
  graduationThresholdUsd: 69420,
};

// Progressive Market Cap Content Milestones (Exclusive to Holders with > $50 USD of $JUICY)
export const JUICY_MILESTONES = [
  {
    phase: "01",
    mcTarget: "$100K",
    mcFull: "$100,000 MC",
    title: "Exclusive Oral Feature",
    format: "Exclusive 4K Oral Master",
    tag: "TARGET 01 // FIRST DROP",
    description: "When market cap reaches $100K in the coming days, Ms Juicy P drops an exclusive, unrated 4K oral feature filmed with a private partner.",
    requirement: "Hold > $50 USD of $JUICY",
    thumbnail: "/juicy/drops/100k_solo_guy.jpg",
    status: "Upcoming First Drop",
    statusBadge: "bg-[#d4fc50]/15 text-[#d4fc50] border-[#d4fc50]/30",
    progressPct: 69,
    active: true,
  },
  {
    phase: "02",
    mcTarget: "$200K",
    mcFull: "$200,000 MC",
    title: "Female Collab",
    format: "Exclusive Girl / Girl Feature",
    tag: "TARGET 02",
    description: "When market cap reaches $200K in the coming days, Ms Juicy P drops an exclusive female collab scene with a top creator.",
    requirement: "Hold > $50 USD of $JUICY",
    thumbnail: "/juicy/drops/200k_female_collab.jpg",
    status: "Locked at $200K",
    statusBadge: "bg-white/5 text-white/50 border-white/10",
    progressPct: 0,
    active: false,
  },
  {
    phase: "03",
    mcTarget: "$500K",
    mcFull: "$500,000 MC",
    title: "Male Collab",
    format: "Full Scene Guy / Girl Feature",
    tag: "TARGET 03",
    description: "When market cap reaches $500K in the coming days, Ms Juicy P drops a full-length unrated male collab feature.",
    requirement: "Hold > $50 USD of $JUICY",
    thumbnail: "/juicy/drops/500k_male_collab.jpg",
    status: "Locked at $500K",
    statusBadge: "bg-white/5 text-white/50 border-white/10",
    progressPct: 0,
    active: false,
  },
  {
    phase: "04",
    mcTarget: "$1M",
    mcFull: "$1,000,000 MC",
    title: "Threesome Feature",
    format: "Ultra-Exclusive Group Feature",
    tag: "TARGET 04 // GRAND FINALE",
    description: "When market cap hits the $1M milestone, Ms Juicy P drops the headline threesome group feature exclusively for token holders.",
    requirement: "Hold > $50 USD of $JUICY",
    thumbnail: "/juicy/drops/1m_threesome.jpg",
    status: "Locked at $1M",
    statusBadge: "bg-white/5 text-white/50 border-white/10",
    progressPct: 0,
    active: false,
  },
];

// Evidence Vault Tiers (Content Sinks)
export const JUICY_VAULT_TIERS = [
  {
    id: "vault-01",
    tierCode: "TIER 01",
    title: "STREET DOSSIER",
    gateLabel: "HOLD ≥ $50 TOKEN",
    costDisplay: "HOLD ≥ $50 USD",
    tokenRequirement: "Zero Tokens Spent",
    subRequirement: "Hold ≥ $50 in Wallet",
    costUsd: 0,
    costTokens: 0,
    isBurn: false,
    isHolderGate: true,
    thumbnail: "/creators/msjuicy_split_poster.jpg",
    format: "32 Uncompressed 35mm Analog Negatives",
    description:
      "Raw analog film roll shot in a Lamborghini Aventador cruising Collins Avenue at 2 AM. Automatically unlocks for any wallet holding at least $50 worth of $JUICY tokens on Robinhood Chain L2.",
    perks: [
      "Hold ≥ $50 USD worth of $JUICY (Zero tokens spent)",
      "32 High-resolution uncompressed 35mm Leica scans",
      "Automatic on-chain Robinhood L2 token gate",
      "Permanent access while maintaining token balance",
    ],
    accent: "#d4fc50",
    badge: "HOLD GATE UTILITY",
  },
  {
    id: "vault-02",
    tierCode: "TIER 02",
    title: "THE BLACK BAG INCINERATOR",
    gateLabel: "BURN $15 IN INCINERATOR",
    costDisplay: "$15.00 USD BURN",
    tokenRequirement: "180,000 $JUICY",
    subRequirement: "Permanent Burn to 0x0...dead",
    costUsd: 15,
    costTokens: 180000,
    isBurn: true,
    isHolderGate: false,
    thumbnail: "/creators/msjuicy_banner.jpg",
    format: "18-Min ProRes 4K Master + Audio Note",
    description:
      "Full-length unrated cinematic feature film recorded in a high-rise suite in Brickell. Feed $JUICY directly into The Incinerator above to decrypt the encrypted stream and permanently incinerate circulating supply.",
    perks: [
      "Burn $15 in $JUICY on Website (180,000 Tokens)",
      "18-Minute master unrated 4K 60fps video stream",
      "Director's uncut commentary & voice memo audio track",
      "Tokens sent permanently to 0x00...dead",
    ],
    accent: "#ffc876",
    badge: "DEFLATIONARY BURN SINK",
  },
  {
    id: "vault-03",
    tierCode: "TIER 03",
    title: "CARTEL BOSS DOSSIER",
    gateLabel: "BURN $50 VIP (LIMITED 50)",
    costDisplay: "$50.00 USD BURN",
    tokenRequirement: "600,000 $JUICY",
    subRequirement: "Strictly Limited · 18/50 Left",
    costUsd: 50,
    costTokens: 600000,
    isBurn: true,
    isHolderGate: false,
    thumbnail: "/creators/msjuicy.jpg",
    format: "Encrypted Direct Hotline + Wax-Sealed Print",
    description:
      "The holy grail. Direct end-to-end encrypted Telegram line with Juicy herself, plus an original metallic archival photo print hand-signed and sealed with black wax, delivered in discreet packaging.",
    perks: [
      "Burn $50 in $JUICY in The Incinerator (600,000 Tokens)",
      "Direct encrypted 1-on-1 access hotline with Juicy",
      "Physical signed metallic analog print in black wax seal",
      "Strictly limited to 50 total syndicate passes (18 remaining)",
    ],
    accent: "#ff453a",
    badge: "ULTRA-RARE VIP SINK",
  },
];

// Cash Incinerator (The Smelter) Ledger & Presets
export const SMELTER_DATA = {
  coreTemperature: "1,850°C",
  totalTokensBurned: 14820000,
  totalTokensBurnedFormatted: "14.8M",
  percentBurned: "1.48%",
  ethBurnedValue: "1.25 ETH",
  usdValueBurnedFormatted: "$3,625",
  burnAddress: "0x000000000000000000000000000000000000dEaD",
  burnPresets: [
    { label: "Torch Stash", tokens: 50000, usd: "$4.10", heat: "+15°C" },
    { label: "Furnace Blast", tokens: 250000, usd: "$20.50", heat: "+65°C" },
    { label: "Mob Meltdown", tokens: 1000000, usd: "$82.00", heat: "+210°C" },
    { label: "Empire Torch", tokens: 5000000, usd: "$410.00", heat: "+850°C" },
  ],
  recentSmelts: [
    {
      id: "smelt-1",
      wallet: "0xb4f...9c12",
      amount: "1,000,000 $JUICY",
      tier: "Tier 03 Decrypt",
      time: "14m ago",
      txHash: "0x3f1a9b8c7d6e5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d",
    },
    {
      id: "smelt-2",
      wallet: "0x82a...e041",
      amount: "250,000 $JUICY",
      tier: "Tier 02 Decrypt",
      time: "42m ago",
      txHash: "0x8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b",
    },
    {
      id: "smelt-3",
      wallet: "0x51c...3321",
      amount: "500,000 $JUICY",
      tier: "Direct Incinerator Burn",
      time: "2h ago",
      txHash: "0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d",
    },
    {
      id: "smelt-4",
      wallet: "0x98f...772a",
      amount: "2,500,000 $JUICY",
      tier: "50% Launch Profit Match",
      time: "5h ago",
      txHash: "0x7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b",
    },
  ],
};

// Syndicate Tokenomics Breakdown
export const JUICY_CAP_TABLE = [
  {
    name: "Public Bonding Curve",
    percentage: 45,
    amount: "450,000,000",
    color: "#d4fc50",
    status: "Fair Launch · Zero Presale",
    description: "Available to everyone on Robinhood Chain L2. 100% fair bonding curve, no insider discounts.",
  },
  {
    name: "Juicy Creator Stash",
    percentage: 20,
    amount: "200,000,000",
    color: "#ffc876",
    status: "6-Mo Cliff · Linear Lock",
    description: "Allocated directly to Juicy and her production team, vesting linearly over 18 months.",
  },
  {
    name: "Raydium L2 Liquidity Pool",
    percentage: 15,
    amount: "150,000,000",
    color: "#5d85ff",
    status: "Auto-Seeded at $69K MC",
    description: "Deposited alongside 4.2 ETH accumulated on the bonding curve once graduated; LP tokens burned.",
  },
  {
    name: "MIKA Protocol Airdrop",
    percentage: 10,
    amount: "100,000,000",
    color: "#a8c3a0",
    status: "Cross-Ecosystem Loyalty",
    description: "Airdropped to verified $MIKA holders to reward the core Mikayla.fun launchpad community.",
  },
  {
    name: "The Incinerator Burn Match",
    percentage: 10,
    amount: "100,000,000",
    color: "#ff453a",
    status: "Deflationary Match Reserve",
    description: "Reserved to match fan burns in The Incinerator 1-to-1 during milestone celebrations.",
  },
];
