// Centralized configuration and content for Ms Juicy P's SCM launch on Robinhood Chain L2

export const JUICY_CONFIG = {
  name: "Ms Juicy P",
  title: "The Vice City SCM Syndicate",
  ticker: "$JUICY",
  ca: "0x123372D9de53D5bEC2988DD2386c7d3666A372a8",
  contractAddress: "0x123372D9de53D5bEC2988DD2386c7d3666A372a8",
  network: "Robinhood Chain L2",
  symbol: "MIKA",
  decimals: 18,
  totalSupply: 1000000000,
  initialSupplyFormatted: "1,000,000,000",
  launchDateUtc: "Friday, Sep 11, 2026 · 5:00 PM UTC",
  targetTimestamp: new Date("2026-09-11T17:00:00Z").getTime(),
  xHandle: "@msjuicy_plenty",
  xUrl: "https://x.com/msjuicy_plenty",
  xFollowers: "80K+ on X",
  repostUrl: "https://x.com/mikaylafun/status/2098092424337711392?s=20",
  partnerHandle: "@CyreneAI",
  partnerUrl: "https://x.com/CyreneAI",
  dexPairUrl: "https://dexscreener.com/search?q=0x123372D9de53D5bEC2988DD2386c7d3666A372a8",
  explorerBaseUrl: "https://robinhoodchain.blockscout.com",
  explorerUrl: "https://robinhoodchain.blockscout.com/address/0x123372D9de53D5bEC2988DD2386c7d3666A372a8",
  burnAddress: "0x000000000000000000000000000000000000dEaD",
  graduationThresholdEth: 4.2,
  graduationThresholdUsd: 69420,
};

// Progressive Market Cap Content Milestones (Exclusive to Holders with > $50 USD of $JUICY)
export const JUICY_MILESTONES = [
  {
    phase: "01",
    mcTarget: "$100K",
    mcFull: "$100,000 MC",
    title: "Exclusive Oral Feature",
    format: "Exclusive 4K Oral Master",
    tag: "TARGET 01 // FIRST DROP",
    description: "When market cap reaches $100K in the coming days, Ms Juicy P drops an exclusive, unrated 4K oral feature filmed with a private partner.",
    requirement: "Hold > $50 USD of $JUICY",
    thumbnail: "/juicy/drops/100k_solo_guy.jpg",
    status: "Upcoming First Drop",
    statusBadge: "bg-[#d4fc50]/15 text-[#d4fc50] border-[#d4fc50]/30",
    progressPct: 69,
    active: true,
  },
  {
    phase: "02",
    mcTarget: "$200K",
    mcFull: "$200,000 MC",
    title: "Female Collab",
    format: "Exclusive Girl / Girl Feature",
    tag: "TARGET 02",
    description: "When market cap reaches $200K in the coming days, Ms Juicy P drops an exclusive female collab scene with a top creator.",
    requirement: "Hold > $50 USD of $JUICY",
    thumbnail: "/juicy/drops/200k_female_collab.jpg",
    status: "Locked at $200K",
    statusBadge: "bg-white/5 text-white/50 border-white/10",
    progressPct: 0,
    active: false,
  },
  {
    phase: "03",
    mcTarget: "$500K",
    mcFull: "$500,000 MC",
    title: "Male Collab",
    format: "Full Scene Guy / Girl Feature",
    tag: "TARGET 03",
    description: "When market cap reaches $500K in the coming days, Ms Juicy P drops a full-length unrated male collab feature.",
    requirement: "Hold > $50 USD of $JUICY",
    thumbnail: "/juicy/drops/500k_male_collab.jpg",
    status: "Locked at $500K",
    statusBadge: "bg-white/5 text-white/50 border-white/10",
    progressPct: 0,
    active: false,
  },
  {
    phase: "04",
    mcTarget: "$1M",
    mcFull: "$1,000,000 MC",
    title: "Threesome Feature",
    format: "Ultra-Exclusive Group Feature",
    tag: "TARGET 04 // GRAND FINALE",
    description: "When market cap hits the $1M milestone, Ms Juicy P drops the headline threesome group feature exclusively for token holders.",
    requirement: "Hold > $50 USD of $JUICY",
    thumbnail: "/juicy/drops/1m_threesome.jpg",
    status: "Locked at $1M",
    statusBadge: "bg-white/5 text-white/50 border-white/10",
    progressPct: 0,
    active: false,
  },
];

// Burn-to-Reveal Content Tiers ($5 / $10 / $25 USD Burns)
// Burn tokens to permanently destroy supply and receive private video content.
// The bigger the burn, the longer the video.
export const JUICY_BURN_TIERS = [
  {
    id: "burn-tier-01",
    tierCode: "TIER 01",
    title: "3-SECOND VIDEO CLIP",
    rewardTitle: "3-Second Video Section",
    gateLabel: "BURN $5 IN INCINERATOR",
    costDisplay: "$5.00 USD BURN",
    tokenRequirement: "60,000 $JUICY",
    subRequirement: "10x Unique Videos (Burn 10x)",
    poolCount: 10,
    poolCountLabel: "10x Unique Drops Available",
    burnCountNotice: "Burn 10x for 10 different clips",
    costUsd: 5,
    costTokens: 60000,
    durationSec: 3,
    durationLabel: "3 Seconds",
    thumbnail: "/juicy/content/snippet_3s_01.png",
    format: "3-Second Video Section",
    description:
      "A quick 3-second unrated teaser clip. You can burn $5 up to 10 times to unlock 10 different unique clips in this pool!",
    perks: [
      "Burn $5 in $JUICY (60,000 Tokens)",
      "10 Different 3-second clips in pool",
      "Burn up to 10x for 10 different clips",
      "Instant MP4 video download included",
    ],
    accent: "#d4fc50",
    badge: "10X UNIQUE DROPS // $5",
    poolBadge: "10X DROPS AVAILABLE",
    durationBadge: "0:03 CLIP",
  },
  {
    id: "burn-tier-02",
    tierCode: "TIER 02",
    title: "30-SECOND VIDEO SNIPPET",
    rewardTitle: "30-Second Video Snippet",
    gateLabel: "BURN $10 IN INCINERATOR",
    costDisplay: "$10.00 USD BURN",
    tokenRequirement: "120,000 $JUICY",
    subRequirement: "6x Unique Videos (Burn 6x)",
    poolCount: 6,
    poolCountLabel: "6x Unique Drops Available",
    burnCountNotice: "Burn 6x for 6 different snippets",
    costUsd: 10,
    costTokens: 120000,
    durationSec: 30,
    durationLabel: "30 Seconds",
    thumbnail: "/juicy/content/snippet_30s_01.png",
    format: "30-Second Video Snippet",
    description:
      "An extended 30-second scene snippet. You can burn $10 up to 6 times to unlock 6 different unique snippets in this pool!",
    perks: [
      "Burn $10 in $JUICY (120,000 Tokens)",
      "6 Different 30-second snippets in pool",
      "Burn up to 6x for 6 different snippets",
      "Instant MP4 video download included",
    ],
    accent: "#30d158",
    badge: "6X UNIQUE DROPS // $10",
    poolBadge: "6X DROPS AVAILABLE",
    durationBadge: "0:30 SNIPPET",
  },
  {
    id: "burn-tier-03",
    tierCode: "TIER 03",
    title: "FULL MINUTES-LONG VIDEO",
    rewardTitle: "Full Uncut Video",
    gateLabel: "BURN $25 IN INCINERATOR",
    costDisplay: "$25.00 USD BURN",
    tokenRequirement: "300,000 $JUICY",
    subRequirement: "3x Full Films (Burn 3x)",
    poolCount: 3,
    poolCountLabel: "3x Unique Full Films Available",
    burnCountNotice: "Burn 3x for 3 different full films",
    costUsd: 25,
    costTokens: 300000,
    durationSec: 532,
    durationLabel: "Full Video (Minutes)",
    thumbnail: "/juicy/content/full_video_03.png",
    format: "Full Minutes-Long Unrated Video",
    description:
      "The complete uncut minutes-long video feature. You can burn $25 up to 3 times to unlock 3 different full master films in this pool!",
    perks: [
      "Burn $25 in $JUICY (300,000 Tokens)",
      "3 Different full-length master films in pool",
      "Burn up to 3x for 3 different full films",
      "Full master MP4 download included",
    ],
    accent: "#ffc876",
    badge: "3X FULL FILMS // $25",
    poolBadge: "3X FULL FILMS AVAILABLE",
    durationBadge: "FULL VIDEO (MINS)",
    highlight: true,
  },
];

// Alias for backwards compatibility
export const JUICY_VAULT_TIERS = JUICY_BURN_TIERS;

// Private Video Pool (Populated with real video files & downloadable assets)
// 10x for $5, 6x for $10, 3x for $25 = 19 Total Unique Drops
export const JUICY_VIDEO_POOL = [
  // 3-Second Teaser Pool ($5 Tier) - 10 Unique Drops Available
  {
    id: "vid-3s-01",
    tierId: "burn-tier-01",
    tierCode: "TIER 01",
    tierCost: "$5 BURN",
    title: "Miami Neon Balcony Flash #1",
    durationSec: 3,
    durationLabel: "0:03",
    sizeLabel: "296 KB",
    poolIndex: 1,
    poolTotal: 10,
    format: "3-Second Video Section",
    thumbnail: "/juicy/content/snippet_3s_01.png",
    videoUrl: "/juicy/content/snippet_3s_01.mp4",
    downloadFilename: "Juicy_3s_Clip_01.mp4",
    caption: "Drop 1 of 10: 3-second high-energy flash on the Miami penthouse terrace.",
    parentVideoId: "vid-full-01",
    parentFilmTitle: "Juicy Vice Feature 01",
  },
  {
    id: "vid-3s-02",
    tierId: "burn-tier-01",
    tierCode: "TIER 01",
    tierCost: "$5 BURN",
    title: "Lambo Aventador Peek #2",
    durationSec: 3,
    durationLabel: "0:03",
    sizeLabel: "294 KB",
    poolIndex: 2,
    poolTotal: 10,
    format: "3-Second Video Section",
    thumbnail: "/juicy/content/snippet_3s_02.png",
    videoUrl: "/juicy/content/snippet_3s_02.mp4",
    downloadFilename: "Juicy_3s_Clip_02.mp4",
    caption: "Drop 2 of 10: 3-second quick glimpse cruising Collins Avenue at midnight.",
    parentVideoId: "vid-full-01",
    parentFilmTitle: "Juicy Vice Feature 01",
  },
  {
    id: "vid-3s-03",
    tierId: "burn-tier-01",
    tierCode: "TIER 01",
    tierCost: "$5 BURN",
    title: "Vice Velvet Tease #3",
    durationSec: 3,
    durationLabel: "0:03",
    sizeLabel: "283 KB",
    poolIndex: 3,
    poolTotal: 10,
    format: "3-Second Video Section",
    thumbnail: "/juicy/content/snippet_3s_03.png",
    videoUrl: "/juicy/content/snippet_3s_03.mp4",
    downloadFilename: "Juicy_3s_Clip_03.mp4",
    caption: "Drop 3 of 10: 3-second raw cut from the private lounge suite.",
    parentVideoId: "vid-full-02",
    parentFilmTitle: "Juicy Vice Feature 02",
  },
  {
    id: "vid-3s-04",
    tierId: "burn-tier-01",
    tierCode: "TIER 01",
    tierCost: "$5 BURN",
    title: "High-Rise Night Smoke #4",
    durationSec: 3,
    durationLabel: "0:03",
    sizeLabel: "285 KB",
    poolIndex: 4,
    poolTotal: 10,
    format: "3-Second Video Section",
    thumbnail: "/juicy/content/snippet_3s_04.png",
    videoUrl: "/juicy/content/snippet_3s_04.mp4",
    downloadFilename: "Juicy_3s_Clip_04.mp4",
    caption: "Drop 4 of 10: 3-second atmospheric clip overlooking the Miami skyline.",
    parentVideoId: "vid-full-02",
    parentFilmTitle: "Juicy Vice Feature 02",
  },
  {
    id: "vid-3s-05",
    tierId: "burn-tier-01",
    tierCode: "TIER 01",
    tierCost: "$5 BURN",
    title: "Brickell Skyline Glance #5",
    durationSec: 3,
    durationLabel: "0:03",
    sizeLabel: "287 KB",
    poolIndex: 5,
    poolTotal: 10,
    format: "3-Second Video Section",
    thumbnail: "/juicy/content/snippet_3s_05.png",
    videoUrl: "/juicy/content/snippet_3s_05.mp4",
    downloadFilename: "Juicy_3s_Clip_05.mp4",
    caption: "Drop 5 of 10: 3-second intimate glimpse from the VIP terrace.",
    parentVideoId: "vid-full-03",
    parentFilmTitle: "Juicy Vice Feature 03",
  },
  {
    id: "vid-3s-06",
    tierId: "burn-tier-01",
    tierCode: "TIER 01",
    tierCost: "$5 BURN",
    title: "Cartel Suite Secret Cut #6",
    durationSec: 3,
    durationLabel: "0:03",
    sizeLabel: "290 KB",
    poolIndex: 6,
    poolTotal: 10,
    format: "3-Second Video Section",
    thumbnail: "/juicy/content/snippet_3s_06.png",
    videoUrl: "/juicy/content/snippet_3s_06.mp4",
    downloadFilename: "Juicy_3s_Clip_06.mp4",
    caption: "Drop 6 of 10: 3-second teaser cut from the headline master film.",
    parentVideoId: "vid-full-03",
    parentFilmTitle: "Juicy Vice Feature 03",
  },
  {
    id: "vid-3s-07",
    tierId: "burn-tier-01",
    tierCode: "TIER 01",
    tierCost: "$5 BURN",
    title: "Miami Ocean Drive Pulse #7",
    durationSec: 3,
    durationLabel: "0:03",
    sizeLabel: "292 KB",
    poolIndex: 7,
    poolTotal: 10,
    format: "3-Second Video Section",
    thumbnail: "/juicy/content/snippet_3s_07.png",
    videoUrl: "/juicy/content/snippet_3s_07.mp4",
    downloadFilename: "Juicy_3s_Clip_07.mp4",
    caption: "Drop 7 of 10: 3-second midnight flash from the master archive tape.",
    parentVideoId: "vid-full-01",
    parentFilmTitle: "Juicy Vice Feature 01",
  },
  {
    id: "vid-3s-08",
    tierId: "burn-tier-01",
    tierCode: "TIER 01",
    tierCost: "$5 BURN",
    title: "South Beach Glimpse #8",
    durationSec: 3,
    durationLabel: "0:03",
    sizeLabel: "289 KB",
    poolIndex: 8,
    poolTotal: 10,
    format: "3-Second Video Section",
    thumbnail: "/juicy/content/snippet_3s_08.png",
    videoUrl: "/juicy/content/snippet_3s_08.mp4",
    downloadFilename: "Juicy_3s_Clip_08.mp4",
    caption: "Drop 8 of 10: 3-second rapid glimpse from the second feature suite.",
    parentVideoId: "vid-full-02",
    parentFilmTitle: "Juicy Vice Feature 02",
  },
  {
    id: "vid-3s-09",
    tierId: "burn-tier-01",
    tierCode: "TIER 01",
    tierCost: "$5 BURN",
    title: "Syndicate Vault Peek #9",
    durationSec: 3,
    durationLabel: "0:03",
    sizeLabel: "295 KB",
    poolIndex: 9,
    poolTotal: 10,
    format: "3-Second Video Section",
    thumbnail: "/juicy/content/snippet_3s_09.png",
    videoUrl: "/juicy/content/snippet_3s_09.mp4",
    downloadFilename: "Juicy_3s_Clip_09.mp4",
    caption: "Drop 9 of 10: 3-second raw cut from the headline master film.",
    parentVideoId: "vid-full-03",
    parentFilmTitle: "Juicy Vice Feature 03",
  },
  {
    id: "vid-3s-10",
    tierId: "burn-tier-01",
    tierCode: "TIER 01",
    tierCost: "$5 BURN",
    title: "Midnight Vice Teaser #10",
    durationSec: 3,
    durationLabel: "0:03",
    sizeLabel: "283 KB",
    poolIndex: 10,
    poolTotal: 10,
    format: "3-Second Video Section",
    thumbnail: "/juicy/content/snippet_3s_10.png",
    videoUrl: "/juicy/content/snippet_3s_10.mp4",
    downloadFilename: "Juicy_3s_Clip_10.mp4",
    caption: "Drop 10 of 10: 3-second grand finale teaser cut.",
    parentVideoId: "vid-full-03",
    parentFilmTitle: "Juicy Vice Feature 03",
  },

  // 30-Second Snippet Pool ($10 Tier) - 6 Unique Drops Available
  {
    id: "vid-30s-01",
    tierId: "burn-tier-02",
    tierCode: "TIER 02",
    tierCost: "$10 BURN",
    title: "Vice Suite Midnight Snippet #1",
    durationSec: 30,
    durationLabel: "0:30",
    sizeLabel: "2.7 MB",
    poolIndex: 1,
    poolTotal: 6,
    format: "30-Second Video Snippet",
    thumbnail: "/juicy/content/snippet_30s_01.png",
    videoUrl: "/juicy/content/snippet_30s_01.mp4",
    downloadFilename: "Juicy_Snippet_30s_01.mp4",
    caption: "Drop 1 of 6: 30-second cinematic snippet overlooking the Biscayne Bay skyline.",
    parentVideoId: "vid-full-01",
    parentFilmTitle: "Juicy Vice Feature 01",
  },
  {
    id: "vid-30s-02",
    tierId: "burn-tier-02",
    tierCode: "TIER 02",
    tierCost: "$10 BURN",
    title: "Brickell Balcony Snippet #2",
    durationSec: 30,
    durationLabel: "0:30",
    sizeLabel: "2.8 MB",
    poolIndex: 2,
    poolTotal: 6,
    format: "30-Second Video Snippet",
    thumbnail: "/juicy/content/snippet_30s_02.png",
    videoUrl: "/juicy/content/snippet_30s_02.mp4",
    downloadFilename: "Juicy_Snippet_30s_02.mp4",
    caption: "Drop 2 of 6: 30-second extended scene from the private midnight balcony session.",
    parentVideoId: "vid-full-01",
    parentFilmTitle: "Juicy Vice Feature 01",
  },
  {
    id: "vid-30s-03",
    tierId: "burn-tier-02",
    tierCode: "TIER 02",
    tierCost: "$10 BURN",
    title: "Private Lounge Motion Snippet #3",
    durationSec: 30,
    durationLabel: "0:30",
    sizeLabel: "2.7 MB",
    poolIndex: 3,
    poolTotal: 6,
    format: "30-Second Video Snippet",
    thumbnail: "/juicy/content/snippet_30s_03.png",
    videoUrl: "/juicy/content/snippet_30s_03.mp4",
    downloadFilename: "Juicy_Snippet_30s_03.mp4",
    caption: "Drop 3 of 6: 30-second unreleased snippet with authentic high-fidelity audio.",
    parentVideoId: "vid-full-02",
    parentFilmTitle: "Juicy Vice Feature 02",
  },
  {
    id: "vid-30s-04",
    tierId: "burn-tier-02",
    tierCode: "TIER 02",
    tierCost: "$10 BURN",
    title: "Miami Velvet After-Hours Snippet #4",
    durationSec: 30,
    durationLabel: "0:30",
    sizeLabel: "2.8 MB",
    poolIndex: 4,
    poolTotal: 6,
    format: "30-Second Video Snippet",
    thumbnail: "/juicy/content/snippet_30s_04.png",
    videoUrl: "/juicy/content/snippet_30s_04.mp4",
    downloadFilename: "Juicy_Snippet_30s_04.mp4",
    caption: "Drop 4 of 6: 30-second cinematic cut from the private late-night session.",
    parentVideoId: "vid-full-02",
    parentFilmTitle: "Juicy Vice Feature 02",
  },
  {
    id: "vid-30s-05",
    tierId: "burn-tier-02",
    tierCode: "TIER 02",
    tierCost: "$10 BURN",
    title: "Syndicate Uncut Lounge Snippet #5",
    durationSec: 30,
    durationLabel: "0:30",
    sizeLabel: "2.7 MB",
    poolIndex: 5,
    poolTotal: 6,
    format: "30-Second Video Snippet",
    thumbnail: "/juicy/content/snippet_30s_05.png",
    videoUrl: "/juicy/content/snippet_30s_05.mp4",
    downloadFilename: "Juicy_Snippet_30s_05.mp4",
    caption: "Drop 5 of 6: 30-second uncut preview from master archive tape #3.",
    parentVideoId: "vid-full-03",
    parentFilmTitle: "Juicy Vice Feature 03",
  },
  {
    id: "vid-30s-06",
    tierId: "burn-tier-02",
    tierCode: "TIER 02",
    tierCost: "$10 BURN",
    title: "Cartel Penthouse Drop Snippet #6",
    durationSec: 30,
    durationLabel: "0:30",
    sizeLabel: "2.7 MB",
    poolIndex: 6,
    poolTotal: 6,
    format: "30-Second Video Snippet",
    thumbnail: "/juicy/content/snippet_30s_06.png",
    videoUrl: "/juicy/content/snippet_30s_06.mp4",
    downloadFilename: "Juicy_Snippet_30s_06.mp4",
    caption: "Drop 6 of 6: 30-second high-def snippet with master stereo sound.",
    parentVideoId: "vid-full-03",
    parentFilmTitle: "Juicy Vice Feature 03",
  },

  // Full Minutes-Long Video Pool ($25 Tier) - 3 Unique Full Videos Available
  {
    id: "vid-full-01",
    tierId: "burn-tier-03",
    tierCode: "TIER 03",
    tierCost: "$25 BURN",
    title: "Juicy Vice Feature 01 (Full Uncut)",
    durationSec: 209,
    durationLabel: "3:29 MINS",
    sizeLabel: "19.2 MB",
    poolIndex: 1,
    poolTotal: 3,
    format: "Full Minutes-Long Uncut Video",
    thumbnail: "/juicy/content/full_video_01.png",
    videoUrl: "/juicy/content/full_video_01.mp4",
    downloadFilename: "Juicy_Full_Feature_01.mp4",
    caption: "Master Film 1 of 3: Complete uncut 3.5-minute feature film with raw master audio.",
    parentVideoId: null,
    childVideoIds: ["vid-30s-01", "vid-30s-02", "vid-3s-01", "vid-3s-02", "vid-3s-07"],
  },
  {
    id: "vid-full-02",
    tierId: "burn-tier-03",
    tierCode: "TIER 03",
    tierCost: "$25 BURN",
    title: "Juicy Vice Feature 02 (Full Uncut)",
    durationSec: 282,
    durationLabel: "4:42 MINS",
    sizeLabel: "25.9 MB",
    poolIndex: 2,
    poolTotal: 3,
    format: "Full Minutes-Long Uncut Video",
    thumbnail: "/juicy/content/full_video_02.png",
    videoUrl: "/juicy/content/full_video_02.mp4",
    downloadFilename: "Juicy_Full_Feature_02.mp4",
    caption: "Master Film 2 of 3: Full-length unrated 4.7-minute feature film recorded in Brickell.",
    parentVideoId: null,
    childVideoIds: ["vid-30s-03", "vid-30s-04", "vid-3s-03", "vid-3s-04", "vid-3s-08"],
  },
  {
    id: "vid-full-03",
    tierId: "burn-tier-03",
    tierCode: "TIER 03",
    tierCost: "$25 BURN",
    title: "Juicy Vice Feature 03 (Headline Unrated)",
    durationSec: 532,
    durationLabel: "8:52 MINS",
    sizeLabel: "48.7 MB",
    poolIndex: 3,
    poolTotal: 3,
    format: "Full Minutes-Long Uncut Video",
    thumbnail: "/juicy/content/full_video_03.png",
    videoUrl: "/juicy/content/full_video_03.mp4",
    downloadFilename: "Juicy_Full_Feature_03.mp4",
    caption: "Master Film 3 of 3: The headline 8.8-minute complete unrated master film with uncut audio.",
    parentVideoId: null,
    childVideoIds: ["vid-30s-05", "vid-30s-06", "vid-3s-05", "vid-3s-06", "vid-3s-09", "vid-3s-10"],
  },
];

// Relationship mapping: Each full film auto-claims all its snippet and clip sub-scenes
export const FULL_VIDEO_CHILDREN = {
  "vid-full-01": ["vid-30s-01", "vid-30s-02", "vid-3s-01", "vid-3s-02", "vid-3s-07"],
  "vid-full-02": ["vid-30s-03", "vid-30s-04", "vid-3s-03", "vid-3s-04", "vid-3s-08"],
  "vid-full-03": ["vid-30s-05", "vid-30s-06", "vid-3s-05", "vid-3s-06", "vid-3s-09", "vid-3s-10"],
};

export const VIDEO_PARENT_MAP = {
  "vid-30s-01": "vid-full-01",
  "vid-30s-02": "vid-full-01",
  "vid-3s-01": "vid-full-01",
  "vid-3s-02": "vid-full-01",
  "vid-3s-07": "vid-full-01",

  "vid-30s-03": "vid-full-02",
  "vid-30s-04": "vid-full-02",
  "vid-3s-03": "vid-full-02",
  "vid-3s-04": "vid-full-02",
  "vid-3s-08": "vid-full-02",

  "vid-30s-05": "vid-full-03",
  "vid-30s-06": "vid-full-03",
  "vid-3s-05": "vid-full-03",
  "vid-3s-06": "vid-full-03",
  "vid-3s-09": "vid-full-03",
  "vid-3s-10": "vid-full-03",
};

// Cash Incinerator (The Smelter) Ledger & Presets
export const SMELTER_DATA = {
  coreTemperature: "1,850°C",
  totalTokensBurned: 14820000,
  totalTokensBurnedFormatted: "14.8M",
  percentBurned: "1.48%",
  ethBurnedValue: "1.25 ETH",
  usdValueBurnedFormatted: "$3,625",
  burnAddress: "0x000000000000000000000000000000000000dEaD",
  burnPresets: [
    { label: "$5 BURN", tokens: 60000, usd: "$5.00", reward: "3s Clip" },
    { label: "$10 BURN", tokens: 120000, usd: "$10.00", reward: "30s Snippet" },
    { label: "$25 BURN", tokens: 300000, usd: "$25.00", reward: "Full Video" },
  ],
  recentSmelts: [
    {
      id: "smelt-1",
      wallet: "0xb4f...9c12",
      amount: "300,000 $JUICY",
      tier: "Full Video ($25 Burn)",
      time: "14m ago",
      txHash: "0x3f1a9b8c7d6e5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d",
    },
    {
      id: "smelt-2",
      wallet: "0x82a...e041",
      amount: "120,000 $JUICY",
      tier: "30s Snippet ($10 Burn)",
      time: "42m ago",
      txHash: "0x8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b",
    },
    {
      id: "smelt-3",
      wallet: "0x51c...3321",
      amount: "60,000 $JUICY",
      tier: "3s Clip ($5 Burn)",
      time: "2h ago",
      txHash: "0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d",
    },
    {
      id: "smelt-4",
      wallet: "0x98f...772a",
      amount: "300,000 $JUICY",
      tier: "Full Video ($25 Burn)",
      time: "5h ago",
      txHash: "0x7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b",
    },
  ],
};

// Syndicate Tokenomics Breakdown
export const JUICY_CAP_TABLE = [
  {
    name: "Public Bonding Curve",
    percentage: 45,
    amount: "450,000,000",
    color: "#d4fc50",
    status: "Fair Launch · Zero Presale",
    description: "Available to everyone on Robinhood Chain L2. 100% fair bonding curve, no insider discounts.",
  },
  {
    name: "Juicy Creator Stash",
    percentage: 20,
    amount: "200,000,000",
    color: "#ffc876",
    status: "6-Mo Cliff · Linear Lock",
    description: "Allocated directly to Juicy and her production team, vesting linearly over 18 months.",
  },
  {
    name: "Raydium L2 Liquidity Pool",
    percentage: 15,
    amount: "150,000,000",
    color: "#5d85ff",
    status: "Auto-Seeded at $69K MC",
    description: "Deposited alongside 4.2 ETH accumulated on the bonding curve once graduated; LP tokens burned.",
  },
  {
    name: "MIKA Protocol Airdrop",
    percentage: 10,
    amount: "100,000,000",
    color: "#a8c3a0",
    status: "Cross-Ecosystem Loyalty",
    description: "Airdropped to verified $MIKA holders to reward the core Mikayla.fun launchpad community.",
  },
  {
    name: "The Incinerator Burn Match",
    percentage: 10,
    amount: "100,000,000",
    color: "#ff453a",
    status: "Deflationary Match Reserve",
    description: "Reserved to match fan burns in The Incinerator 1-to-1 during milestone celebrations.",
  },
];
